### ISSUE TITLE
Connect Tech - NGX004-02 - Quark Carrier + NVIDIA® Jetson Nano™ Module + Active Thermal

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/cad-libraries#101]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  |[ carrier ](https://connecttech.com/product/quark-carrier-nvidia-jetson-nano/) , [heatsink](https://connecttech.com/product/nvidia-jetson-nano-active-heat-sink/) , [jetson nano](https://developer.nvidia.com/embedded/jetson-nano)                |
| Project              | 4k head     |
| Alias Creo           | CONNECTTECH_NGX004-02                        |
| IIT-Code             | [if available]                         |
| Applicant            | @salvi-mattia                |
| Supervisor           | @fiorisi             |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
![immagine](https://user-images.githubusercontent.com/43994292/173585424-e5aa4d4c-ec17-4ccf-bcd0-cb26443ea116.png)

![immagine](https://user-images.githubusercontent.com/43994292/173593202-8bf6cec6-8d49-4dc9-913b-1a2638ce8885.png)

![immagine](https://user-images.githubusercontent.com/43994292/173590730-e438cefd-f0b5-44ad-9022-815288e84618.png)

![immagine](https://user-images.githubusercontent.com/43994292/173590612-777c4a2e-d610-42c6-aff7-3ee445d5ed77.png)

![immagine](https://user-images.githubusercontent.com/43994292/173598073-889b24f1-6de3-4540-bc63-eb4287c062cc.png)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [ ] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by salvi-mattia** [comment]
16446 - Quark Carrier + NVIDIA® Jetson Nano™ Module + Active Thermal NGX004-02

we need to check weight and mounting while the assembly will be here

**Comment by MrAndrea** [comment]
Hi @pattacini, @masa, why did you assign only the Wingst code 16446 for this group of components and not 3 different codes?

![image](https://user-images.githubusercontent.com/20459541/176866704-f964aab4-d2f4-4404-b811-e54ed6377982.png)

cc @marcellosavoldi

**Comment by MrAndrea** [comment]
Thanks.
Now we have to replace the Nano board with the Xavier NX as written in [this comment](https://github.com/icub-tech-iit/study-icub-head/issues/15#issuecomment-1168439612), and the Xavier NX has 16487 as code. 
Do we add a new Wingst code for the new group or do we split the 3 components?

**Comment by fiorisi** [comment]
Thanks @salvi-mattia for the detailed comment.

Probably at this point it would be useful to have a clear list and connection schematics using the dedicated issue template: https://github.com/icub-tech-iit/mechatronics/issues/new/choose

![image](https://user-images.githubusercontent.com/8970230/176893188-f86eeaa6-cba6-405d-9a80-4d7c3fdbca5d.png)

**Comment by salvi-mattia** [comment]
let's assume from the OP that the whole code weights 46+33+1.4= 80.4g
this seems not to be coherent with [this](https://github.com/icub-tech-iit/study-icub-head/issues/6#issuecomment-1135864747)
at the moment we do not have a physical specimen to be weighed

**Comment by salvi-mattia** [comment]
talking with @fiorisi fe found out that the correct weight of the here discussed boards pack
is 46+33+1.4+18 (https://www.waveshare.com/jetson-nano-module.htm) = 98.4g

**Comment by salvi-mattia** [comment]
![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/43994292/e4dd7e9b-da1f-4cbd-87e9-bd5dd3a3e035)

i guess we can close @fiorisi
