### ISSUE TITLE
[Digital View] - [MIP-1000] - [OLED / LCD Controller Board]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#107]
| Description          | MIPI DSI OLED / LCD Controller Board        |
|:---------------------|:---------------------------------------|
| Datasheet component  | [digital-view-product-guide-2022.pdf](https://github.com/icub-tech-iit/cad-libraries/files/9102982/digital-view-product-guide-2022.pdf), [mip-1000-brochure.pdf](https://github.com/icub-tech-iit/cad-libraries/files/9102997/mip-1000-brochure.pdf)  |
| Project              | ergoCub     |
| Alias Creo           | Digitalview_MIP-1000              |
| IIT-Code             | 16509                |
| Applicant            | Michele Gesino, @Mick3Lozzo              |
| Supervisor           | Ugo Pattacini, @pattacini        |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

![image](https://user-images.githubusercontent.com/15085666/178756105-22814476-aa04-49e7-bc74-0bd44b53a0f1.png)

### Notes:

Bought via Aliexpress.

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [ ] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with the manufacturer and at least one supplier.

**Comment by Mick3Lozzo** [comment]
Created code in WinGST, but we don't have an official supplier, it has been bought via Alexpress.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/178755572-105159fd-faa8-476a-9f78-8d3c3cc4d3bd.png)

Weighted mass, 18 g.

**Comment by marcellosavoldi** [comment]
Can you create a middle plane in the USB connector and flat connector to facilitate the assembly of the plug components?
what do you think?
![image](https://user-images.githubusercontent.com/53296021/178933568-1bf1269c-607d-4622-9e38-94024857204c.png)

**Comment by fiorisi** [comment]
> Created code in WinGST, but we don't have an official supplier, it has been bought via Alexpress.

cc @icub-tech-iit/silo-electr

**Comment by fgarini** [comment]
> > Created code in WinGST, but we don't have an official supplier, it has been bought via Alexpress.
> 
> cc @icub-tech-iit/silo-electr

May Electronica be a suitable candidate for this request of offer?
They already supplied to us the flexible display (cfr purchases#1739)

**Comment by Mick3Lozzo** [comment]
> Can you create a middle plane in the USB connector and flat connector to facilitate the assembly of the plug components? what do you think?

Ok.

**Comment by Mick3Lozzo** [comment]
This component has been discontinued. Closing issue.
