### ISSUE TITLE
RLS - MRA053BC030DSE00, MB053SPL20MENT00 - Magnetic code wheel & AksIM2 encoder

### ISSUE THREAD

**Issue by divyashah** [icub-tech-iit/cad-libraries#116]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [AksIM2 Datasheet](https://www.rls.si/eng/fileuploader/download/download/?d=1&file=custom%2Fupload%2FMBD01_10EN_datasheet_bookmark.pdf)                  |
| Project              | ergoCub (& future) joints     |
| Alias Creo           | RLS_MRA053BC030DSE00, RLS_MB053SPL20MENT00                         |
| IIT-Code             | [if available]                         |
| Applicant            | Divya Shah, @divyashah                |
| Supervisor           | Andrea Mura, @MrAndrea                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [ ] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by divyashah** [comment]
**RLS_MRA053BC030DSE00** 
![image](https://user-images.githubusercontent.com/16266334/184147261-87c25828-4d7d-42d2-b621-886f377bc25c.png)

---

**RLS_MB053SPL20MENT00**
![image](https://user-images.githubusercontent.com/16266334/184147162-3bd6c2ba-9cf6-4c72-b711-264e134ef234.png)

**Comment by marcellosavoldi** [comment]
@divyashah , can you check if is present the sys MATE_CONN in that connector?
in case , can you add it in the same position of the our molex one?

**Comment by divyashah** [comment]
Thanks @marcellosavoldi for pointing it out. 

The `MATE_CONN` csys was missing so I updated the file with the previous commit. 
![image](https://user-images.githubusercontent.com/16266334/185182829-cd3578d8-29c8-4985-b58f-87842b892267.png)

**Comment by divyashah** [comment]
These are being considered for the large joint design. 
Once we finalize the design and decide to purchase them, maybe @MrAndrea could help in adding these components to WINGST.

**Comment by MrAndrea** [comment]
Ok @divyashah, I will wait for the finalized design to add them on Wingst.

**Comment by divyashah** [comment]
This Aksim2 encoder and magnetic disk was intended for the large joint. However, we won't be using them for now. 
I suggest we can skip adding them to WINGST. However, we can keep them in the `cad-libraries` as they are already committed. In that case we can close this issue. 

What do you think ? @fiorisi @marcellosavoldi
