### ISSUE TITLE
ECAD - FBEADAR-0804-600RX100MHZ-0A1 - 10835 - Ferrite beads array

### ISSUE THREAD

**Issue by Lawproto** [icub-tech-iit/cad-libraries#122]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link or attachment ] *               |       |
| Manufacturer info  | [Manufacturer name + serial number] * |       |
| Alias Creo         | [Alias or filename MCAD] \**          |       |
| MCAD Contact       | Lorenzo Protopapa @Lawproto        |       |
| ECAD Contact       | Francesco Garini @fgarini        |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)
![immagine](https://user-images.githubusercontent.com/84333301/190645866-94f9a7e4-4869-4526-8808-954d30bf9ba9.png)

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by fgarini** [comment]
![image](https://user-images.githubusercontent.com/84333807/190670862-76937b1d-36b0-4c58-9e7a-c11c04206cce.png)

![image](https://user-images.githubusercontent.com/84333807/190670737-d3ff4686-acc5-445d-acfe-2addf4f14657.png)
pitch 1-5 0.9mm in ecad
