### ISSUE TITLE
Magfine - MAGFINE_NDC_MAGNET - Neodymium N35 Magnets with hole

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#140]
| Description          | Neodymium N35 circular emagnets with countersunk hole |                            
|:---------------------|:---------------------------------------|
| Datasheet component  | [Neodymium countersunk circular magnets](https://www.magfine.it/it/user_data/neodymium_disc_countersunk.php)                  |
| Project              | ergoCub     |
| Alias Creo           | MAGFINE_NDC_MAGNET                        |
| IIT-Code             | [if available]                         |
| Applicant            | Michele Gesino, @Mick3Lozzo              |
| Supervisor           | Ugo Pattacini, @pattacini                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
 Example of instance NDC0023
 
[NDC0023_2D.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10708007/NDC0023_2D.pdf)
[NDC0023_SPEC.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10708009/NDC0023_SPEC.pdf)
[NDC0023_3D.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10708010/NDC0023_3D.pdf)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Mick3Lozzo** [comment]
For the material, I added the Neodymium N35 to the material library, considering the fact that all the physical properties of the material were known @icub-tech-iit/silo-mech.

The EDU-COM converter still is not working.

**Comment by fiorisi** [comment]
> For the material, I added the Neodymium N35 to the material library, considering the fact that all the physical properties of the material were known @icub-tech-iit/silo-mech.
> 
> For now, the only instance I added is **17122**.

@Mick3Lozzo did you open a Pull Request?
If not please delete the material and open a PR.

**Comment by Mick3Lozzo** [comment]
> @Mick3Lozzo did you open a Pull Request? If not please delete the material and open a PR.

Added @fiorisi.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/218494139-bfd24c29-35fd-4cfe-87a2-7435b02c1f2d.png)

BTW @fiorisi, these are the magnets we are using in R1. 👆🏻

Maybe we need another \*.mtl file, or we could use the same kind of neodymium.
