### ISSUE TITLE
Xsens - MTi-630 - IP 51 rated IMU

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#143]
| Description          | Inertial sensor MTi-630-AHRS                             |
|:---------------------|:---------------------------------------|
| Datasheet component  |    [MTi_600_series_Datasheet-2940224.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10792474/MTi_600_series_Datasheet-2940224.pdf) |
| Project              | ergoCub    |
| Alias Creo           | XSENS_MTI-630-AHRS          |
| IIT-Code             | [if available]                         |
| Applicant            | Michele Gesino, @Mick3Lozzo    |
| Supervisor           | Ugo Pattacini, @pattacini            |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

[MTi 600-series STEP files.zip](https://github.com/icub-tech-iit/cad-libraries/files/10792634/MTi.600-series.STEP.files.zip)

[MTi 600-series Hardware Integration Manual.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10802788/MTi.600-series.Hardware.Integration.Manual.pdf)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/220344303-047aa06c-a8fc-4967-a394-b843c64458e3.png" width="300">

Weight: **37 g**

**Comment by marcellosavoldi** [comment]
@Mick3Lozzo If you can, put a SYS Mate_conn, with the plug connector as a cosmetic in the 'PLUGS' layer as written in the [WIKI](https://github.com/icub-tech-iit/cad-libraries/wiki/Create-a-ECAD-component-in-CREO#mandatory-coordinate-system-for-plug-components).
This is useful for defining the overall dimensions.
thanks

**Comment by fiorisi** [comment]
@Mick3Lozzo please add also a frame that defines the measuremetn frame. Please post also the page of the manual that defines its location, as a future reference.

**Comment by Mick3Lozzo** [comment]
> @Mick3Lozzo please add also a frame that defines the measurement frame. Please post also the page of the manual that defines its location, as a future reference. Check other sensors to use the same naming convention.

@fiorisi the frame has been already added following the manual indications (pages 27-37 of the attached manual).

<img src="https://user-images.githubusercontent.com/15085666/220649545-6c0e8075-cc21-4a97-aa79-feb3748d0fbc.png" width="400">

<img src="https://user-images.githubusercontent.com/15085666/220649308-74f7815e-f012-487c-a59d-f98bbb02a426.png" width="400">

<img src="https://user-images.githubusercontent.com/15085666/220652892-384e0bc1-22b3-4ad4-b7f0-54681fa973a2.png" width="400">

I also added as a hidden copy geometry a possible connector suggested in the manual, but there are a lot of possible choices, and the correct one is still to define.

<img src="https://user-images.githubusercontent.com/15085666/220654130-fa6fdae4-2f00-4450-a5f2-0140d55614c2.png" width="400">

**Comment by fiorisi** [comment]
> @fiorisi the frame has been already added following the manual indications (pages 27-37 of the attached manual).

Great! Can you check how it is named in other sensors, like FT or boards with accelerometers.

> I also added as a hidden copy geometry a possible connector suggested in the manual, but there are a lot of possible choices, and the correct one is still to define.

Then I would remove it.

**Comment by marcellosavoldi** [comment]
Hi @Mick3Lozzo , I just talked to @fiorisi  about the plug connector and explained to him the usefulness of the connector's cosmetics.
He also agrees that it can be useful to keep it in the hidden level...
If we then use another type of connector we can make an envelope with a connector with the maximum size of all or simply overlap them.... then we will decide.
is it ok for you?

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/220938991-f8008f80-6895-4b79-b204-ad3e082437c5.png" width="400">

I was joking! 😶 I verified the IMU we bought, and in the box, there are included **exactly** the connectors I choose.

For now, I am going to maintain them, but I think there is some idea to buy a cable with an adapter. Maybe.

@marcellosavoldi @fiorisi

**Comment by Mick3Lozzo** [comment]
@fiorisi @marcellosavoldi, @maggia80 said that we are going to realize a cable by ourselves and the COM Express probably has a UAART connector too, so I suppose that [this one](https://user-images.githubusercontent.com/15085666/220938991-f8008f80-6895-4b79-b204-ad3e082437c5.png) is definitely the correct one.

**Comment by Mick3Lozzo** [comment]
Created WinGST code **17298**.

@fiorisi @marcellosavoldi

**Comment by fiorisi** [comment]
@Mick3Lozzo once the part is done feel free to close the issue.
