### ISSUE TITLE
ECAD - [RES-AXIAL-1R2-75W-ALU-5TOL] - [17138] - [Aluminium housed wirewound resistor, 1R2, 75W, 5%]

### ISSUE THREAD

**Issue by Andrea-Mor** [icub-tech-iit/cad-libraries#144]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link or attachment ] *               |       |
| Manufacturer info  | [Manufacturer name + serial number] * |       |
| Alias Creo         | [Alias or filename MCAD] \**          |       |
| MCAD Contact       | Andrea Mor @Andrea-Mor              |       |
| ECAD Contact       | Francesco Garini @fgarini               |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by Andrea-Mor** [comment]
Hi @fgarini 
can you please work on those points?
![image](https://user-images.githubusercontent.com/79802725/220962597-273fd200-0b3a-4d2b-90cd-dcb15d6fa500.png)

**Comment by fgarini** [comment]
Code: 7138 
Description: Aluminium housed wirewound resistor, 1R2, 75W, 5%
Alias: RES-AXIAL-1R2-75W-ALU-5TOL

Datasheet | [[link or attachment](http://wingst.icub.iit.local/direct_download.php?LINK=%2F%2Fiiticubstor01.iit.local%2Ficub-tech%2Fmechatronics%2FDatasheet%2FResistors%2FRS%2FRS-75+Aluminium+Housed+Resistors.pdf) ]|  
Manufacturer info | RS 1754152* |  
Alias Creo | [Alias or filename MCAD] ** |  
MCAD Contact | Andrea Mor @Andrea-Mor |  
ECAD Contact | Francesco Garini @fgarini |  
Maintainer | Marcello Savoldi, @marcellosavoldi

**Comment by Andrea-Mor** [comment]
Done, closing.
cc @fiorisi
