### ISSUE TITLE
Intel - RealSense D405 - Depth Camera

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#146]
| Description          |  Intel® RealSense™ Depth Camera D405      |
|:---------------------|:---------------------------------------|
| Datasheet component  |  [Intel-RealSense-D400-Series-Datasheet-November-2022.pdf](https://github.com/icub-tech-iit/cad-libraries/files/10993577/Intel-RealSense-D400-Series-Datasheet-November-2022.pdf)  |
| Project              | iCub   |
| Alias Creo           | INTEL_REALSENSE_D405                       |
| IIT-Code             | 17231              |
| Applicant            | Michele Gesino @Mick3Lozzo               |
| Supervisor           | Nicolo Genesio, @Nicogene                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

[Intel_RealSense_D405_CAD_external.zip](https://github.com/icub-tech-iit/cad-libraries/files/10993610/Intel_RealSense_D405_CAD_external.zip)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/225696430-e3b05352-ccad-4e3d-8eb1-1d24cbd1e518.png" width="400">

Weight: **60 g**

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/225701979-21d2f080-5350-4aac-ad32-9b775d968527.png" width="400">

Corrected weight.

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/225727696-a86b1806-2f22-4ffd-827b-5629f8e5f3e7.png" width="400">

<img src="https://user-images.githubusercontent.com/15085666/225727822-0144c3e2-db96-41c1-aa13-d7942df41a70.png" width="400">

<img src="https://user-images.githubusercontent.com/15085666/225730909-5edd872e-afc2-4c1b-8345-251f27798f18.png" width="400">

Added depth camera zero plane and CSYS references.

**Comment by Mick3Lozzo** [comment]
AMI guys are thinking to buy this item, and it does not seem to be WinGST standardized.

**Comment by marcellosavoldi** [comment]
all commercial parts that can be mounted on the robot should have the Wingst code.
can you help them to create it?

**Comment by Mick3Lozzo** [comment]
> all commercial parts that can be mounted on the robot should have the Wingst code. can you help them to create it?

I created the code **17231** @marcellosavoldi.

**Comment by Lawproto** [comment]
Depth Camera?

![telecamera-no](https://user-images.githubusercontent.com/84333301/226412162-0419d29d-9055-4055-9b8a-2f8a86215639.gif)

**Comment by Mick3Lozzo** [comment]
> Depth Camera?

Another one. More compact. More kawaii.
