### ISSUE TITLE
 ECAD -[AD9522-1BCPZ]-[15046]-[Programmable 12 LVDS/24 CMOS]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#16]
| |  |
|:---|:---|
| Datasheet component  | [link or attachment ] |
|maker info | [Maker brand + serial number] |
| Alias Creo | [AD9522-1BCPZ] |
| MCAD Contact | [Marcello Savoldi] [@marcellosavoldi ] |
| ECAD Contact | [Simeone Dussoni] [@simeonedussoni ] |

Image with origin e PIN 1 position by PADS:

Attachment:

Notes:
Component for UZCB

### Madatory information/action:
- [ ] Added IIT-CODE
- [ ] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [ ] Added label "Libraries-Request" (could be automatic )
- [ ] Link/datasheet/drawing or other informations needing to create the libraries parts
- [ ] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)

without these informations is not possible proceed with the request issue

**Comment by marcellosavoldi** [comment]
@simeonedussoni , have you some more information about this component?
I noted also wingst info are missing.

**Comment by marcellosavoldi** [comment]
I found this.... could be?
![image](https://user-images.githubusercontent.com/53296021/100118968-a8539280-2e76-11eb-9ade-9f0f96426132.png)

**Comment by simeonedussoni** [comment]
ies it is
