### ISSUE TITLE
Harwin - R30-6700394 - Spacer, cylindrical, int.diam. 3.2mm, through hole, h=3mm, nylon

### ISSUE THREAD

**Issue by Lawproto** [icub-tech-iit/cad-libraries#165]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [see Wingst]                 |
| Project              | ergoCub lower arm   |
| Alias Creo           | HARWIN_R30-6700394                   |
| IIT-Code             | 4591                       |
| Applicant            | Lorenzo Protopapa, @Lawproto                 |
| Supervisor           | Luca Fiorio, @fiorisi               |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Lawproto** [comment]
See commit above. Closing.

**Comment by Lawproto** [comment]
@Mick3Lozzo it is a duplicated code. I say we just keep one of them, replace all the where used of the other and then delete it. Anyway, I suggest that the library component issue stay close since it is mostly unrelated to this problem.

**Comment by Mick3Lozzo** [comment]
@Lawproto I did a check and a component with a 4591 alias does not even exist, maybe I can correct the alias of [this](https://private-user-images.githubusercontent.com/15085666/331539892-0ba7614f-bdc3-4189-be90-8a57ab9bd3ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA1NzMsIm5iZiI6MTcxNjE5MDI3MywicGF0aCI6Ii8xNTA4NTY2Ni8zMzE1Mzk4OTItMGJhNzYxNGYtYmRjMy00MTg5LWJlOTAtOGE1N2FiOWJkM2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzIyMjA2MTQ3ZjVjNjNiYWMyNmQ0NWE3OWVjYWVkYTM2YTE0ZDg1MDNlYjI3NWQ0YjhiNzUzNDE5YzYxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFFz0--EEvj4Ii0w37M-7OzSG_molPrIC4NL_8lYnPI) and make [this one](https://private-user-images.githubusercontent.com/15085666/331541041-3cebebad-5ef0-47db-a8a2-0ae7d9d4a161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA1NzMsIm5iZiI6MTcxNjE5MDI3MywicGF0aCI6Ii8xNTA4NTY2Ni8zMzE1NDEwNDEtM2NlYmViYWQtNWVmMC00N2RiLWE4YTItMGFlN2Q5ZDRhMTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNjFhYTg2MmNlNjA1Y2JjZTY1NzY4YjlkMTEwYzMxZDMyZWQxNzA4NzU0ZTMzZWY1NWI3OTFlM2FmZDhiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-X52-e1bwzbsDWH15WpUnEiTmfY9d198tlaEAsw-Cb8) obsolete.

cc @Fabrizio69

**Comment by Lawproto** [comment]
@Fabrizio69 I checked, I please ask you to do this:
- Substitute `17845` for `4591` inside this BoM:
![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/84333301/b5f042cd-a191-4213-819e-d4abb2e5e9a2)
- Delete `17845`.

Everything will fall back into place.

**Comment by Fabrizio69** [comment]
Done: deleted `cod.17845`

**Comment by Miche19** [comment]
@Mick3Lozzo @Lawproto after a check, only 20 pieces of the code 4591 are present in the warehouse

Fixed real quantities in WinGst

cc: @Fabrizio69
