### ISSUE TITLE
ECAD - [Molex_46562-9321 ] - [18167] - [new BMS connectors]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#169]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link or attachment ] *               |       |
| Manufacturer info  | [Molex 46562-9321 and Molex [46437-9321](https://github.com/icub-tech-iit/cad-libraries/issues/188)r] * |       |
| Alias Creo         | [Molex_46562-9321 and [Molex_46437-9321](https://github.com/icub-tech-iit/cad-libraries/issues/188)] \**          |       |
| MCAD Contact       | Marcello Savoldi, @marcellosavoldi                 |       |
| ECAD Contact       | Maurizio Borgagni, @maurizbo              |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)
TBD
###  Attachments (optional)
see:
https://www.molex.com/en-us/products/part-detail/465629321
https://www.molex.com/en-us/products/part-detail/464379321

### Plug connector information (mandatory for connectors "board to wire")

the above connectors connect to each other.
are both to be assembled on a circuit board

### Notes (optional)
La scheda la sta eseguento la ditta Biamino , ma sarebbe meglio avere i connettori anche noi.
le issue di riferimento:
https://github.com/icub-tech-iit/ergocub2-design-upperbody/issues/23
https://github.com/icub-tech-iit/ergocub2-design-upperbody/issues/25
https://github.com/icub-tech-iit/electronics-boards/issues/370
https://github.com/icub-tech-iit/electronics-boards/issues/312

### Checklist:
- [ ] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [X] Added assignees (min. 1 mechanical + 1 electrical contact).
- [X] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [ ] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [X] Added details about the PLUG connector (added datasheet, or Wingst code).
- [ ] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
Il fornitore esterno sta eseguendo la sbrogliatura della nuova BMS.

Ing. Alessandro Piazza
Biamino & Figli SpA
via Geirato 104c - 16138 Genova - Italia
Tel  010 8355 098 Int. 218
www.biamino.com

Visto che dovremo poi creare la scheda PLUG, sarebbe meglio per eseguire le verifiche del caso creare i connettori in oggetto.
Attualmente ho creato i connettori a CAD e mi è stata spedita una scheda preliminare ( un file step):
![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/8f557926-edbe-4b3a-8c14-37de4102fd35)

i connettori in oggetto sono cosi posizionati ( preliminarmente) :
![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/0bcea1a2-44e0-46e9-a973-9b4d62e2ea60)

**Comment by maurizbo** [comment]
Ciao @marcellosavoldi nel primo ti direi pin A1 in alto a sn ( 180 gradi rispetto al disegno attuale) e origine al centro che componente. Per default quando lo dovró fare lo disegberó cosí

**Comment by marcellosavoldi** [comment]
![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/1492d6cc-10c0-41b1-8404-9e3386092dc4)

Created librarie part: MOLEX_46562-9321

**Comment by marcellosavoldi** [comment]
Requirements ( first preliminary list ):

1. type of measurement: Torque only
2. Torque sensitivity from 0 to 300Nm
3. Yield strength of the sensor shaft : 450Nm
4. approximate dimensions $\phi$ 65mm Max x 10mm Height
5. Fixing holes : 6 for side

**Comment by marcellosavoldi** [comment]
mating info:
![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/b592fef4-d14b-4a96-b2d1-04590f745512)

**Comment by fgarini** [comment]
ciao @marcellosavoldi a way to remember we have the CAD figures could be to add wingst code with aliases and purchaseable P/N in the right categories, what do you think?

**Comment by fgarini** [comment]
For the sample in the past I contacted a sales representative or alternative there is the module here:
https://tools.molex.com/molex/smp/amesamplereq

Alternatively you can buy them via usual suppliers [rs, farnell mouser](https://octopart.com/search?q=MOLEX+46437-9321&currency=USD&specs=0) (..)

**Comment by marcellosavoldi** [comment]
> For the sample in the past I contacted a sales representative or alternatively there is the contact module here: https://tools.molex.com/molex/smp/amesamplereq
> 
> Alternatively you can buy them via usual suppliers [rs, farnell mouser](https://octopart.com/search?q=MOLEX+46437-9321&currency=USD&specs=0) (..)

I knew Visioli who is now retired... do you know any Molex representatives?
I wait for you to create the codes on WIngst before closing this Issue?

**Comment by maurizbo** [comment]
I added another molex contact (person)
Giorgio Badino
Sales Development Account Manager
+34 611476644
[giorgio.badino@molex.com](mailto:giorgio.badino@molex.com)

**Comment by marcellosavoldi** [comment]
How can we proceed?
Do we also create the library figures in PADS before closing the issue as previously discussed?

@fgarini , @maurizbo , @fiorisi

**Comment by maurizbo** [comment]
Hi @marcellosavoldi you can close it, perhaps when it will be needed the footprint will be made in Xpedition (the new EDA tool)
@fgarini @fiorisi

**Comment by marcellosavoldi** [comment]
with @fiorisi  we talked about the fact that it would be better to do them, but if you think not I can close...

**Comment by maurizbo** [comment]
Ok @marcellosavoldi we will speak about at the tomorrow SU

cc @andreaderito

**Comment by marcellosavoldi** [comment]
it was decided to close the issue.
Electronic libraries parts will be made later

**Comment by marcellosavoldi** [comment]
The issue was reopened to verify a few things ...
see [HERE](https://github.com/icub-tech-iit/electronics-boards/issues/443)

**Comment by marcellosavoldi** [comment]
We'll use this issue only for the connector 46562-9321
About the [46437-9321]( https://github.com/icub-tech-iit/cad-libraries/issues/188) an other issue already exist

I'm going to cerrect the title from 
ECAD - [Molex_46562-9321 and Molex_46437-9321] - [IIT-CODE] - [new BMS connectors]
to
ECAD - [Molex_46562-9321 ] - [18167] - [new BMS connectors]

**Comment by marcellosavoldi** [comment]
@maurizbo , @andresoll , @fgarini 

Can you confirm the new ALIAS name " **MOLEX_EXT_TEN60_15PIN_MALE_90** " for the Molex code 46562-9321 ?

**Comment by fgarini** [comment]
@marcellosavoldi i checked wingst and the P/N there are now correct, take them as reference

# FEMALE 0 DEGREE
![image](https://github.com/icub-tech-iit/cad-libraries/assets/84333807/09aa54b7-4ea2-42b2-a356-0511b90c8c0f)
![image](https://github.com/icub-tech-iit/cad-libraries/assets/84333807/4c1a5eec-c206-49b2-b502-858091fdc669)

# MALE 90 DEGREE
![image](https://github.com/icub-tech-iit/cad-libraries/assets/84333807/cffb057d-d3ce-4391-b86f-7fdf29fedc93)
![image](https://github.com/icub-tech-iit/cad-libraries/assets/84333807/a0cadae0-fca5-45fe-8594-c1268ba0c60f)

all right from your side?

**Comment by marcellosavoldi** [comment]
OK, I'm going to remane to MOLEX_EXT_TEN60_15PIN_FEM_STR

**Comment by marcellosavoldi** [comment]
Can we close @maurizbo ?
