### ISSUE TITLE
 ECAD - DRV8844PWP - 15144 - Motor Driver

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#17]
| |  |
|:---|:---|
| Datasheet component  | see Wingst |
|maker info | Texas Instruments - DRV8844PWP |
| Alias Creo | [Alias or filename MCAD] |
| MCAD Contact | @marcellosavoldi  |
| ECAD Contact | @maurizbo  |

Image with origin e PIN 1 position by PADS:

![image](https://user-images.githubusercontent.com/53302701/100085738-b42a5f00-2e4c-11eb-969b-3ae0dfba812a.png)

Attachment:

Notes:

### Madatory information/action:
- [x] Added IIT-CODE
- [x] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [x] Added label "Libraries-Request" (could be automatic )
- [x] Link/datasheet/drawing or other informations needing to create the libraries parts
- [x] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)

without these informations is not possible proceed with the request issue

**Comment by fiorisi** [comment]
@maurizbo this component has been added to the library?

**Comment by maurizbo** [comment]
Done, the task can be closed
