### ISSUE TITLE
 ECAD - STM32H745IIK6 - 14464 - Microcontroller dual core ARM Cortex-M4

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#18]
| |  |
|:---|:---|
| Datasheet component  | see Wingst |
|maker info | ST Microelectronics - STM32H745IIK6 |
| Alias Creo | [Alias or filename MCAD] |
| MCAD Contact | @marcellosavoldi  |
| ECAD Contact | @maurizbo  |

Image with origin e PIN 1 position by PADS:

![image](https://user-images.githubusercontent.com/53302701/100088930-3452c380-2e51-11eb-9346-9c301474c694.png)

Attachment:

Notes:

### Madatory information/action:
- [x] Added IIT-CODE
- [x] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [x] Added label "Libraries-Request" (could be automatic )
- [x] Link/datasheet/drawing or other informations needing to create the libraries parts
- [x] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)

without these informations is not possible proceed with the request issue

**Comment by fiorisi** [comment]
@maurizbo this component has been added to the library?

**Comment by marcellosavoldi** [comment]
I can see it in the libraries...
![image](https://user-images.githubusercontent.com/53296021/146527467-d8341555-a129-421b-ae58-1d249d98d1f4.png)

we can close
