### ISSUE TITLE
Faulhaber - 3216W024BXTH - Electric motor 24V

### ISSUE THREAD

**Issue by Lawproto** [icub-tech-iit/cad-libraries#183]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [link or attachment ]                  |
| Project              | ergoCub neck    |
| Alias Creo           | 	FAULHABER_3216W024BXTH                        |
| IIT-Code             | [if available]                         |
| Applicant            | Lorenzo Protopapa, @Lawproto                 |
| Supervisor           | Nicolò Genesio, @Nicogene                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [ ] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Lawproto** [comment]
The item is ready with the mass of the datasheet, to be updated when the physical object will be available.

![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/84333301/4d42a40f-5bf7-443d-a029-6c0b5893da7e)

**Comment by marcellosavoldi** [comment]
Hi @Lawproto ,
it might be useful to enter threads, axes and it might be useful to run a 'recognition pattern' ...
What do you think?
we usually do this and many times it is useful when assembling...

**Comment by Lawproto** [comment]
@marcellosavoldi sounds good, can you offer an example so I can copy?

**Comment by Lawproto** [comment]
We agreed T2T to check `FAULHABER_3216X024BXTH` for reference.

**Comment by Lawproto** [comment]
I seized the day and added the info coming from the datasheet into annotations, as well.

![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/84333301/f172cd46-00cd-4e04-9ffd-21df44d6a25d)
![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/84333301/eac92b48-c517-46f2-b711-1a427cff7555)
![immagine](https://github.com/icub-tech-iit/cad-libraries/assets/84333301/8a616c3b-c442-4ded-9d6e-deca6bc1df2b)


I like the idea of having all the useful information in the 3D. Who knows where this may bring us in the future.
cc @icub-tech-iit/silo-mech

**Comment by Lawproto** [comment]
> I have to update the string `3216X024BXTH` to `3216W024BXTH` everywhere.

✅ CAD updated.

**Comment by Lawproto** [comment]
Mass updated. I was hoping for a `666` but what can you do about that. Closing.

![immagine](https://github.com/user-attachments/assets/39056dc9-e68a-4d26-a6e1-76d1676aac45)
