### ISSUE TITLE
ECAD - [ MOLEX_EXT_TEN60_15PIN_MALE_90 ] - [18163] - [connector for BAT_CONN , plugs of BMS]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#188]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link](https://www.molex.com/en-us/products/part-detail/464379321)  |       |
| Manufacturer info  | Molex 46437-9321 |       |
| Alias Creo         | MOLEX_EXT_TEN60_15PIN_MALE_90   |       |
| MCAD Contact       | Marcello Savoldi  ,   @marcellosavoldi      |       |
| ECAD Contact       | Andrea Solari, @andresoll (cc @Maurizio Borgagni, @maurizbo )  |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/7efb02a8-0410-4f32-b725-52d395e27506)

### Plug connector information (mandatory for connectors "board to wire")
MOLEX_46562-9321

### Notes (optional)

IIT-CODE 18163

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [ ] Added details about the PLUG connector (added datasheet, or Wingst code).
- [ ] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
https://github.com/icub-tech-iit/mechatronics/issues/87

**Comment by maurizbo** [comment]
I'd suggest to change the alias from 
MOLEX_46437-9321
to
MOLEX_EXT_TEN60_15PIN

cc @marcellosavoldi @andresoll

**Comment by maurizbo** [comment]
EXTreme Ten60Power Right-Angle Plug with Side Guides, 1 DC Power Circuit, 15 Signal Circuits, 1 DC Power Circuit, Press Fit Tail

@marcellosavoldi All it's seemed to me too much long

This is a kind of component that will not be used anymore ...so could be useful to avoid similarity

**Comment by marcellosavoldi** [comment]
the [procedures](https://github.com/icub-tech-iit/cad-libraries/wiki/Create-a-ECAD-component-in-CREO) read as follows:
`The file name must be decided in accordance with the electronic team.`
... so we can proceed as you think best.

**Comment by marcellosavoldi** [comment]
Connector renamed as required

> For The final name of the MOLEX 46437-9321
> 
> MOLEX_EXT_TEN60_15PIN

**Comment by marcellosavoldi** [comment]
@maurizbo , @andresoll ,
can we close this issue?

**Comment by maurizbo** [comment]
Hi @marcellosavoldi  can you wait just the quick check from @andresoll in the pads figure ? We can close tomorrow

**Comment by marcellosavoldi** [comment]
@maurizbo , @andresoll , @fgarini 

about the comment [HERE](https://github.com/icub-tech-iit/electronics-boards/issues/443#issuecomment-2220821219)
Can you confirm the new ALIAS name " **MOLEX_EXT_TEN60_15PIN_MALE_90** " for the Molex code 46437-9321 ?

**Comment by marcellosavoldi** [comment]
@maurizbo ,
if you want check your model Vs the CAD model , following some dimensions:

![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/4c5ebfc9-84a5-4654-93be-97fd3558dc4d)

**Comment by marcellosavoldi** [comment]
SOME DIMENSIONS TO CHECK THE PADS LIBRARIES FIGURE:
![image](https://github.com/user-attachments/assets/5ce4ec72-ecc9-4abd-9256-a6d5edf98b39)

**Comment by fgarini** [comment]
## figure to adjust
(it's not symmetrical)
![image](https://github.com/user-attachments/assets/93624291-c875-4377-af67-a689f93cb691)

![image](https://github.com/user-attachments/assets/637ad003-05c5-4a61-a53b-d3cc892296e7)
Check consequently:
![image](https://github.com/user-attachments/assets/e0fed553-355f-4cf4-a7e6-867ef5431857)
![image](https://github.com/user-attachments/assets/4ea66bef-6c8d-4ac5-8ded-ab622a2f1d9b)

**Comment by valegagge** [comment]
Hi guys,
I saw there are still 2 tasks to complete this task. Is it correct or can we close the issue?
