### ISSUE TITLE
ECAD - [PICOBLADE-7X1-MALESTR-P125] - [3947] - [Picoblade 7x1]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#189]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [[MOLEX 53398-0771](https://www.molex.com/en-us/products/part-detail/533980771#mates-with-use-with) ] *               |       |
| Manufacturer info  | MOLEX 53398-0771 |       |
| Alias Creo         | PICOBLADE-7X1-MALESTR-P125 \**          |       |
| MCAD Contact       |     Marcello Savoldi, @marcellosavoldi          |       |
| ECAD Contact       | Maurizio Borgagni, @maurizbo               |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

![image](https://github.com/icub-tech-iit/cad-libraries/assets/53296021/721c8453-1523-4435-87b2-5db22a04c115)

### Plug connector information (mandatory for connectors "board to wire")

51021-0700

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
@maurizbo , Can you check the origin position on PADS?

**Comment by maurizbo** [comment]
![image](https://github.com/icub-tech-iit/cad-libraries/assets/53302701/cdef27b7-2024-4564-9ee3-08d2e376433d)

**Comment by maurizbo** [comment]
I changed the origin of this connector because it was in a strange positions. The cards where it is used are only test equipment or not  icub tech card. Anyway in the past it has been used here

![image](https://github.com/icub-tech-iit/cad-libraries/assets/53302701/9e7eb4c1-0d7b-4668-9fe6-ac450c1a424b)

**Comment by marcellosavoldi** [comment]
Se La figura PADS è ok si può chiudere.

Confermi @maurizbo ?
