### ISSUE TITLE
ECAD - [	MINIFIT-2X2-FEM90-P420 ] - [11285] - [Mini-Fit Jr. Header - 9° - 2x2 ]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#192]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [LINK  ](https://www.molex.com/en-us/products/part-detail/26013128)             |       |
| Manufacturer info  | Molex  26013128|       |
| Alias Creo         | MINIFIT-2X2-FEM90-P420         |       |
| MCAD Contact       | Marcello Savoldi, @marcellosavoldi          |       |
| ECAD Contact       | Maurizio Borgagni , @maurizbo             |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

![image](https://github.com/user-attachments/assets/50af4bde-bebb-418b-a854-25030dce7274)

### Plug connector information (mandatory for connectors "board to wire")

[Molex 39013048](https://www.molex.com/en-us/products/part-detail/39013048)

### Notes (optional)

Già esistente su Wingst, mancano però tutte le figure

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [ ] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by valegagge** [comment]
@marcellosavoldi @maurizbo news on this task?

**Comment by valegagge** [comment]
Don't use anymore.
