### ISSUE TITLE
ECAD - [PCA9615DPZ] - [18258] - [component for I2C ext]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#199]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [NXP - PCA9615 I2C bus extender.pdf](https://github.com/user-attachments/files/17488023/NXP.-.PCA9615.I2C.bus.extender.pdf) |       |
| Manufacturer info  | NXP semiconductor PCA9615DPZ |       |
| Alias Creo         | PCA9615DPZ        |       |
| MCAD Contact       | Marcello Savoldi , @marcellosavoldi                |       |
| ECAD Contact       | Maurizio Borgagni , @maurizbo            |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

@maurizbo ,  can you added the image here?

### Checklist:
- [ ] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [ ] Added assignees (min. 1 mechanical + 1 electrical contact).
- [ ] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [ ] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [ ] Added details about the PLUG connector (added datasheet, or Wingst code).
- [ ] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
![Image](https://github.com/user-attachments/assets/30a59cd4-30cd-4067-b4dd-cd223ef50bc4)

![Image](https://github.com/user-attachments/assets/2fe972f3-166e-452d-956d-f8e58aeda671)

**Comment by marcellosavoldi** [comment]
I checked the other similar compionents... the origin is in the middle...is for this the same?
![Image](https://github.com/user-attachments/assets/9846f694-42c3-4422-ba16-e047599e978c)

**Comment by maurizbo** [comment]
Hi @marcellosavoldi sorry for the delay, here you are the 0 rotation of the U1 component (origin in the center).

![Image](https://github.com/user-attachments/assets/06936fa2-590e-4de1-b58e-49c6ecd46292)

cc @andresoll

**Comment by marcellosavoldi** [comment]
done
![Image](https://github.com/user-attachments/assets/b2cd7bfe-940b-47bf-a4e4-1eebe8f3a8fc)
