### ISSUE TITLE
 ECAD - LT8620EUDD - 15156- Voltage regulator, switching, step-down

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#25]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * |  |
|maker info | [Maker brand + serial number] * |  |
| Alias Creo | [LT8620EUDD] **|  |
| MCAD Contact | @marcellosavoldi  |  |
| ECAD Contact | @maurizbo |  |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 
(this info is mandatory):
![image](https://user-images.githubusercontent.com/53302701/100360935-dc0af580-2ff9-11eb-92fc-ac5b196e4fbe.png)

###  Attachments 
(if present):
...

### Plug connector information 
( in case of connector "board to wire" is mandatory)
...

### Notes ( if needed):
...

### Madatory information/action:
(without these informations is not possible proceed with the request issue)
- [ ] Added IIT-CODE
- [ ] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [ ] Added label "Libraries-Request" (could be automatic )
- [ ] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [ ] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [ ] Detail about the PLUG connector (added datasheet, or Wingst code)

**Comment by marcellosavoldi** [comment]
done!
