### ISSUE TITLE
 ECAD - IND-3X3-3UH3-2A2-20TOL - 15159 - Power inductor 3X3X2

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#26]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * | |
|maker info | [Maker brand + serial number] * | |
| Alias Creo | [Alias or filename MCAD] **| |
| MCAD Contact | @marcellosavoldi  |  |
| ECAD Contact | @maurizbo  | |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 
(this info is mandatory):
![image](https://user-images.githubusercontent.com/53302701/100371233-c4d30480-3007-11eb-8e0b-e9af80a7434b.png)

###  Attachments 
(if present):
...

### Plug connector information 
( in case of connector "board to wire" is mandatory)
...

### Notes ( if needed):
...

### Mandatory information/action:
(without these informations is not possible proceed with the request issue)
- [ ] Added IIT-CODE
- [ ] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [ ] Added label "Libraries-Request" (could be automatic )
- [ ] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [ ] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [ ] Detail about the PLUG connector (added datasheet, or Wingst code)

**Comment by marcellosavoldi** [comment]
done!
