### ISSUE TITLE
Modification part request-[ISO7045_Z]-[added M3x14 into family table]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#27]
|               |                         |
|:--------------|:------------------------|
| type of part  | [MCAD ]            |
| Alias Creo    | ISO7045_Z (add V3-14--_-_ISO7045_CZ )       |
| IIT-Code      | [2542]            |
| Applicant     | Marcello Savoldi, @marcellosavoldi  |
| supervisor    | Luca Fiorio, @fiorisi  |
| other people involved |  @icub-tech-iit/silo-mech       |

## Description and motivation of the changing request: <br>
see https://github.com/icub-tech-iit/cad-libraries/issues/8

## details for the modification
added variant **V3-14--_-_ISO7045_CZ**
added a different description in the row with a different material
Could be better modify the description as Wingst
here the file excel with the right description for M1.6, M2, M2.5, M4.... we have to modify others
[new_description_iso7045_z.xlsx](https://github.com/icub-tech-iit/cad-libraries/files/5608935/new_description_iso7045_z.xlsx)

## To be filled in by mainteiners or department manager
* [ ] modification approved
* [ ] modification checked and ready for pushing to repo

**Comment by fiorisi** [comment]
@marcellosavoldi can we close this issue?

**Comment by marcellosavoldi** [comment]
yes... the screw has been added
![image](https://user-images.githubusercontent.com/53296021/146526655-28c8880e-28da-414a-beec-5f94c2c725a0.png)
