### ISSUE TITLE
 ECAD - USB3_C_1054500101 -15047 - Molex USB 3.1 tiype C - 24 pin

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#30]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * | |
|maker info | [Maker brand + serial number] * | |
| Alias Creo | [Alias or filename MCAD] **| |
| MCAD Contact | [name Surname] [nick git] |  |
| ECAD Contact | [name Surname] [nick git] | |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 
(this info is mandatory):

![image](https://user-images.githubusercontent.com/53302701/102247651-7dea7780-3f00-11eb-9711-8f202cda71b3.png)
Origin in the middle between pin 25 and 26 same X axis

###  Attachments 
(if present):
...

### Plug connector information 
( in case of connector "board to wire" is mandatory)
...

### Notes ( if needed):
...

### Madatory information/action:
(without these informations is not possible proceed with the request issue)
- [ ] Added IIT-CODE
- [ ] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [ ] Added label "Libraries-Request" (could be automatic )
- [ ] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [ ] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [ ] Detail about the PLUG connector (added datasheet, or Wingst code)
@

**Comment by marcellosavoldi** [comment]
done
