### ISSUE TITLE
 ECAD-[DF12NC-20DS-0.5V(51)]-[ 15299]-[ Mezzanine connector, straight, SMD]

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#33]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * | |
|maker info | [Maker brand + serial number] * | |
| Alias Creo | [Alias or filename MCAD] **| |
| MCAD Contact | [name Surname] [nick git] |  |
| ECAD Contact | [name Surname] [nick git] | |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 

![image](https://user-images.githubusercontent.com/53302701/112388111-f4162b80-8cf2-11eb-9962-5ae10e33a5a2.png)

...

###  Attachments 
(if present):
...

### Plug connector information 

DF12NC(3.5)-20DP-0.5V(51) - DF12NC(4.0)-20DP-0.5V(51) - DF12NC(5.0)-20DP-0.5V(51)
Change height 3.5, 4.0, 5.0
### Notes ( if needed):
...

### Madatory information/action:
(without these informations is not possible proceed with the request issue)
- [x] Added IIT-CODE
- [x] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [x] Added label "Libraries-Request" (could be automatic )
- [x] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [x] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [x] Detail about the PLUG connector (added datasheet, or Wingst code)

**Comment by marcellosavoldi** [comment]
I created it...
but we have to change the ALIAS in 

> hirose-df12nc-20ds-0v5

 ....  @maurizbo , can you confirm?

![image](https://user-images.githubusercontent.com/53296021/130208374-fdf84a59-baa9-47bd-9257-a830a202b1d7.png)

**Comment by maurizbo** [comment]
About the alias it was already OK

![image](https://user-images.githubusercontent.com/53302701/130455648-3e8ccdb0-4ae1-40b3-a8e5-6066c52c7e9a.png)
