### ISSUE TITLE
 ECAD -[ DSS45160FDB ]-[ 15288 ]-[ COMPLEMENTARY NPN/PNP Transistor ]

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#34]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * | |
|maker info | [Maker brand + serial number] * | |
| Alias Creo | [Alias or filename MCAD] **| |
| MCAD Contact | [name Surname] [nick git] |  |
| ECAD Contact | [name Surname] [nick git] | |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 
![image](https://user-images.githubusercontent.com/53302701/112393624-ae119580-8cfb-11eb-81cb-aae9e671b517.png)

...

###  Attachments 
(if present):
...

### Plug connector information 
( in case of connector "board to wire" is mandatory)
...

### Notes ( if needed):
...

### Madatory information/action:
(without these informations is not possible proceed with the request issue)
- [x] Added IIT-CODE
- [x] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [x] Added label "Libraries-Request" (could be automatic )
- [x] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [x] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [x] Detail about the PLUG connector (added datasheet, or Wingst code)

**Comment by marcellosavoldi** [comment]
it was already existing...
I converted it in commercial license part
