### ISSUE TITLE
 ECAD-[DF12NC-4_0-20DP-0V5]-[15309]-[Mezzanine, 20 contacts, 2 rows, female, p.0.5mm, Straight, SMD

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#35]
### request: 
| description| box to edit| notes|
|:---|:---|:---|
| Datasheet component  | [link or attachment ] * | |
|maker info | [Maker brand + serial number] * | |
| Alias Creo | [HIROSE-DF12NC-4_0-20DP-0V5] **| |
| MCAD Contact | [name Surname] [nick git] |  |
| ECAD Contact | [name Surname] [nick git] | |

legend:
 "*" = To compile only if this information are missing in the database (Wingst)
  "**" = To compile only it is a preliminary name

### Image with origin e PIN 1 position by PADS 
![image](https://user-images.githubusercontent.com/53302701/113673729-a538a080-96b9-11eb-897d-7799b0905162.png)

###  Attachments 
(if present):
...

### Plug connector information 
( in case of connector "board to wire" is mandatory)
DF12NC-20DS-0V5

### Notes ( if needed):
...

### Madatory information/action:
(without these informations is not possible proceed with the request issue)
- [x] Added IIT-CODE
- [x] Added assignees ( min. 1 mechanical + min. 1 Elettrical contact)
- [x] Added label "Libraries-Request" (could be automatic )
- [x] Link/datasheet/drawing or others information ( or information into Wingst database compiled)
- [x] The detail about the PIN 1 and the orientation of the origin of the component (img/sketch/printscreen)
- [x] Detail about the PLUG connector (added datasheet, or Wingst code)

**Comment by marcellosavoldi** [comment]
DONE!
![image](https://user-images.githubusercontent.com/53296021/117425662-47e77780-af23-11eb-982e-17ad0f6f3eb1.png)
