### ISSUE TITLE
TQ_ILM50x08 & TQ_ILM50x14 - New frameless motors

### ISSUE THREAD

**Issue by divyashah** [icub-tech-iit/cad-libraries#36]
|Description | Field |
|:---|:---|
| Datasheet component  | [Web link](https://www.tq-group.com/filedownloads/files/products/robodrive/data-sheets/en/DRVA_DB_Servo-Kits_ILM_EN_Rev408_Web.pdf) |
| Project | Generic |
| Alias Creo | TQ_ILM50x08 & TQ_ILM50x14 |
| IIT-Code | [if available] |
| Applicant | Divya Shah, @divyashah  |
| Supervisor | Marcello Savoldi, @marcellosavoldi  |
| Maintainer | Marcello Savoldi, @marcellosavoldi     |

### Notes:
New frameless motors from TQ systems as purchased in the issue icub-tech-iit/purchases#1042 need to be added in the `cad-libraries`. 
Web links for the two motors are [ILM50x08](https://www.tq-group.com/en/products/tq-robodrive/servo-kits-brakes-and-sensors/ilm50x08/) and [ILM50x14](https://www.tq-group.com/en/products/tq-robodrive/servo-kits-brakes-and-sensors/ilm50x14/).

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Edited the [parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by fiorisi** [comment]
Great @divyashah!

Can you check on the manufacturer website, or directly contact the supplier?
As seen together there are some STEP files in the ZIP attached to https://github.com/icub-tech-iit/electronics-boards/issues/76#issuecomment-788860587.

Nevertheless I would check that is the correct revision before adding it to the library.

**Comment by divyashah** [comment]
> As seen together there are some STEP files in the ZIP attached to icub-tech-iit/electronics-boards#76 (comment).
>
> Nevertheless I would check that is the correct revision before adding it to the library.

It seems that the step file in the zip and also the files on the manufacturer website are the latest revision. The motors received comply with all the major dimensions.

**Comment by divyashah** [comment]
> Remember also to add the [part parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components), in particular follow this section for the frameless motors: https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#categories-for-frame-less-motors

Thanks @fiorisi  for pointing this out. 
Following the these guidelines and the discussion with @marcellosavoldi , we decided to design the components as follows: 
- Rotors : designed with **"features"** and assigned the type `COSM`
- Stators (with PCB) : imported from the STEP file and assigned the type `MOTR` 

The following assembly and part files will then be added to the [`cad-libraries\libraries\motors_and_gearboxes`](https://github.com/icub-tech-iit/cad-libraries/tree/master/libraries/motors_and_gearboxes):
 
```
TQ_ILM50x08.asm
├── TQ_ILM50x08_STATOR.prt
└── TQ_ILM50x08_ROTOR.prt
```

```
TQ_ILM50x14.asm
├── TQ_ILM50x14_STATOR.prt
└── TQ_ILM50x14_ROTOR.prt
```
 
> Then I think that it is also worth to align the CAD files with WINGST.

I do not have access to WINGST. Let me know how we can proceed with that part.

**Comment by divyashah** [comment]
Here are some renders of the assemblies:

**TQ_ILM50x08**
![render_50x08](https://user-images.githubusercontent.com/16266334/122375508-91d06e00-cf63-11eb-854d-7e7b59784687.jpg)


**TQ_ILM50x14**
![render_50x14](https://user-images.githubusercontent.com/16266334/122375267-59c92b00-cf63-11eb-9e59-004c6dae7bf4.jpg)

**Comment by divyashah** [comment]
The following assembly and part files were committed to the [`cad-libraries\libraries\motors_and_gearboxes`](https://github.com/icub-tech-iit/cad-libraries/tree/master/libraries/motors_and_gearboxes):
 
```
TQ_ILM50x08.asm
├── TQ_ILM50x08_STATOR.prt
└── TQ_ILM50x08_ROTOR.prt
```

```
TQ_ILM50x14.asm
├── TQ_ILM50x14_STATOR.prt
└── TQ_ILM50x14_ROTOR.prt
```

Can someone review it once ?? @fiorisi  @marcellosavoldi 

cc @icub-tech-iit/silo-mech

**Comment by fiorisi** [comment]
Great job @divyashah 🚀  Here some comments:

> I do not have access to WINGST. Let me know how we can proceed with that part.

I've requested the user: https://github.com/icub-tech-iit/tickets/issues/1411

> designed with "features" and assigned the type COSM

In this case please **double check** the dimensions and all the small features (e.g. chamfers). Even a small error (less than a mm) could result in a not working prototype.

Did you check the mass properties? Also for the imported part. I've added a small guide here https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts

There are some parameters that shall be removed in commercial parts. See https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components

For what concerns the description I would as to @MrAndrea to check if is fine (it is an electric motor and this description will be copied also in WINGST)
![image](https://user-images.githubusercontent.com/8970230/122409814-ba686000-cf83-11eb-9cee-3344139a2749.png)


cc @icub-tech-iit/silo-mech

**Comment by MrAndrea** [comment]
@fiorisi I added the `TQ` company on the _Anagrafica/Costruttori_ on Wingst:

![image](https://user-images.githubusercontent.com/20459541/122572915-8312b580-d04e-11eb-83a2-6d3a404e5610.png)

Regarding the description, I think it is quite good but you can add something in order to have similar sentence like other motor codes.

**Comment by divyashah** [comment]
Thanks @fiorisi for the feedback! 
I made updates in the parts as below: 


> In this case please **double check** the dimensions and all the small features (e.g. chamfers). Even a small error (less than a mm) could result in a not working prototype.

I didn't find a separate drawing of the rotor itself. However, I did cross check the dimensions from the assembly drawings and from the physical rotor component.  

> * Did you check the mass properties? Also for the imported part. I've added a small guide here https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts

I updated the mass properties for each part as well the assembly as per these guidelines. 

> * There are some parameters that shall be removed in commercial parts. See https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components

I removed the additional parameters as mentioned here. I kept `DESIGNED` and `DRAWN` only for the **Rotor** parts which were manually designed with "features".  Let me know if I should remove those too. 

> * This distance was taken from the datasheet?
>   ![image](https://user-images.githubusercontent.com/8970230/122410830-8d687d00-cf84-11eb-9a8a-7b2f0f3a4a08.png)

Initially, I tried to place the rotor equidistant in the magnet area of the stator, so I used the distance as shown in the Fig. Now, I have updated this distance as per the datasheet. 

Below are the links to the drawing files: 
- [Drawing-ILM50x08](https://www.tq-group.com/filedownloads/files/products/robodrive/drawing/drawing_ilm50x08_rev.0102.pdf)
- [Drawing-ILM50x14](https://www.tq-group.com/filedownloads/files/products/robodrive/drawing/drawing_ilm50x14_rev.0101.pdf)

**Comment by divyashah** [comment]
Thanks @MrAndrea for the feedback!

> Regarding the description, I think it is quite good but you can add something in order to have similar sentence like other motor codes.

I added the description that @marcellosavoldi suggested, which was in the description in the purchase order on `WINGST`. 

![image](https://user-images.githubusercontent.com/16266334/123979066-ae878f80-d9c0-11eb-99d8-13c9e214b37a.png)

Could you maybe point me to one or two motors as example from which I can update the description ??

**Comment by fiorisi** [comment]
Great @divyashah!

> I updated the mass properties for each part as well the assembly as per these guidelines.

The mass properties shall be assigned only to the parts, not to the assemblies. 

> I removed the additional parameters as mentioned here. I kept DESIGNED and DRAWN only for the Rotor parts which were manually designed with "features". Let me know if I should remove those too.

Fine for me.

> Initially, I tried to place the rotor equidistant in the magnet area of the stator, so I used the distance as shown in the Fig. Now, I have updated this distance as per the datasheet.

Great! Can you also add the datasheets to our [common folder](https://github.com/icub-tech-iit/cad-mechanics#other-material)? There is a `Motors` folder, inside feel free to create a folder for this manufacturer. In this way we can the reference it from WINGST.

**Comment by divyashah** [comment]
> Great! Can you also add the datasheets to our [common folder](https://github.com/icub-tech-iit/cad-mechanics#other-material)? There is a `Motors` folder, inside feel free to create a folder for this manufacturer. In this way we can the reference it from WINGST.

I created a sub-folder named `TQ`. I added some datasheet files and also the .zip that was available from the supplier. I will keep updating it as I have more details.

**Comment by fiorisi** [comment]
Great @divyashah.

I would remove the `Motor` in both the assemblies. If we use actuation for certain simulations should be located in the top level assembly. Otherwise different joint have the same `Motor`.
![image](https://user-images.githubusercontent.com/8970230/124285135-ee2fb200-db4d-11eb-92d4-72b94c7405ff.png)

If I am not mistaken the weight of the ILM50x08 [should be 87 g](https://www.tq-group.com/en/products/tq-robodrive/servo-kits-brakes-and-sensors/ilm50x08/)
In the CAD assembly I see a different mass. Where did you take the weight of the rotor and stator separately? I found only the assembly weight.
![image](https://user-images.githubusercontent.com/8970230/124286121-e91f3280-db4e-11eb-8dde-01c54555362c.png)

**Comment by fiorisi** [comment]
Also the ILM50x14 [should be 135 g](https://www.tq-group.com/en/products/tq-robodrive/servo-kits-brakes-and-sensors/ilm50x14/). While the CAD assembly seems to be 62.
![image](https://user-images.githubusercontent.com/8970230/124287294-23d59a80-db50-11eb-8c02-231356dd495b.png)

**Comment by divyashah** [comment]
> I would remove the `Motor` in both the assemblies. If we use actuation for certain simulations should be located in the top level assembly. Otherwise different joint have the same `Motor`.

Yes, that's true. I will remove the `Motor` from the assemblies. 


> If I am not mistaken the weight of the ILM50x08 [should be 87 g](https://www.tq-group.com/en/products/tq-robodrive/servo-kits-brakes-and-sensors/ilm50x08/)

Yes, the assembly weights for the motors (stator + rotor) for ILM50x08 and ILM50x14 are 87g and 135g respectively. 

> In the CAD assembly I see a different mass. Where did you take the weight of the rotor and stator separately? I found only the assembly weight.

I did not find the different mass specifically in datasheets. But I physically weighed the individual stator and rotor components to have the weight distribution as below: 

|     Part     |  Measured Mass [kg] | CAD Volume [mm^3] | Calculated Density [kg/mm^3] |
|:------------:|:---------:|:-------------:|:-----------------:|
| TQ_ILM50x08_Rotor  |   0.021   |    2692.87    |   7.798 e-6   |
| TQ_ILM50x08_Stator |   0.066   |    12309.5    |   5.361 e-6   |
| TQ_ILM50x14_Rotor  |   0.034   |    4385.29    |   7.753 e-6   |
| TQ_ILM50x14_Stator |   0.101   |    17872.7    |   5.651 e-6   |


---
In the CAD files, if I check the `Assigned` mass property it shows the expected mass value (~ 87g). However, the `Computed` values are different as shown in images above. 
![image](https://user-images.githubusercontent.com/16266334/124471171-d69a3880-dd9c-11eb-9bd7-972b48998f68.png)


Maybe we can cross check this together ?? 
cc @fiorisi

**Comment by divyashah** [comment]
We understood that the difference in the mass properties arise due to a newer way of using mass properties in Creo 7.0. 
Here is a screenshot describing which parameters to use to assign a density to a part. 

![image](https://user-images.githubusercontent.com/16266334/124585500-a367b000-de55-11eb-94af-ad7239653a37.png)

Here are the reference links to the related guides from PTC Support for Creo 7.0: 
- [About Working with Mass Property Parameters](https://support.ptc.com/help/creo/creo_pma/r7.0/usascii/index.html#page/model-based_definition%2Fabout_working_with_mass_property_parameters.html%23) 
- [Specifying the Density of a Part](https://support.ptc.com/help/creo/creo_pma/r7.0/usascii/index.html#page/model-based_definition/specifying_the_density_of_a_part.html) 

If I remove all materials assigned (as per our guidelines on [Mass Properties of Commercial Parts](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts)), then there is no `PTC_MASS_DENSITY` parameter available. 
If I change the legacy parameter `MP_DENSITY` and assign the calculated `average density`, the mass of the Creo part is updated. 


However, there is some rounding error.  The reported mass is about **83g** where as the actual mass should be around **87g.**  

![image](https://user-images.githubusercontent.com/16266334/124586717-13c30100-de57-11eb-9df8-813bf14ff6e4.png)

cc @fiorisi

**Comment by fiorisi** [comment]
Thanks @divyashah, @salvi-mattia is experiencing the same issue. 

This could be a good case for the DEDA support team (cc @marcellosavoldi)

**Comment by divyashah** [comment]
I did the following updates on the motor files: 
- Removed `Motor` from the assembly files. 
- Added a **index hole** in the Rotors that was previously missing. 
- Changed the legacy parameter `MP_DENSITY` to assign the calculated density and updated the mass properties. 

Now the computed mass from the CAD files are as follows:
- TQ_ILM50x08 : **~83g** (rated mass = 87g)
- TQ_ILM50x14 : **~142g** (rated mass = 135g)


The unit for density used in CREO is `kg/mm^3` and the assigned values are of the order of `10^-6`. Creo rounds off these density values and this results in the error in the computed mass as mentioned above. 

> This could be a good case for the DEDA support team (cc @marcellosavoldi)

So, it wold be worth asking DEDA support team if there is a better way to assign the calculated density or if we can avoid these rounding errors.

**Comment by MrAndrea** [comment]
> Could you maybe point me to one or two motors as example from which I can update the description ??

Hi @divyashah, you can select the category `MO - Motors` on Wingst and for example write `frameless` in the description, then see the items:

![image](https://user-images.githubusercontent.com/20459541/125101688-cb1b7a00-e0da-11eb-81bf-2cfbae0f61fc.png)

**Comment by divyashah** [comment]
Thanks @MrAndrea for the reference! 

I updated the CAD assembly files with the following description (adding rated Torque (Tr) and rated current (Ir)). 

`TQ_ILM50x08 frameless stator-rotor assembly; Tr=0.3 Nm; Ir=5.1 A`

`TQ_ILM50x14 Frameless stator-rotor assembly; Tr=0.54 Nm; Ir=5.3 A`

However, I think we still need to add these motors to the WINGST database.

**Comment by fiorisi** [comment]
Great @divyashah! 🚀 

Just few questions.

> Added a index hole in the Rotors that was previously missing

Do you have a reference to document the hole location here?

> Changed the legacy parameter MP_DENSITY to assign the calculated density and updated the mass properties

Did you find this solution in the Creo help? Do you have a page to link?

Which is the description of the `_rotor` and `_stator` `prt`?

> However, I think we still need to add these motors to the WINGST database.

Yes, in this case we add only the `prt` not the assembly. @marcellosavoldi can show you how to manually create the WINGST codes or how to create a BOM to import the codes automatically.

**Comment by divyashah** [comment]
Thanks @fiorisi for the feedback,

> > Added a index hole in the Rotors that was previously missing
> 
> Do you have a reference to document the hole location here?

Yes, it is given in the motor drawings. Here are the snapshots of it. 

![image](https://user-images.githubusercontent.com/16266334/125631818-aba394b9-46dc-42f1-8b39-f174f600e6f6.png)

![image](https://user-images.githubusercontent.com/16266334/125631536-2dcc6f4b-f1cb-420e-84f5-ed98263f94a1.png)


 
> > Changed the legacy parameter MP_DENSITY to assign the calculated density and updated the mass properties
> 
> Did you find this solution in the Creo help? Do you have a page to link?

Yes, it was mentioned in the CREO help. I added the links in this comment above. ([#36 Comment](https://github.com/icub-tech-iit/cad-libraries/issues/36#issuecomment-874661606)).
> Here are the reference links to the related guides from PTC Support for Creo 7.0:
> 
> * [About Working with Mass Property Parameters](https://support.ptc.com/help/creo/creo_pma/r7.0/usascii/index.html#page/model-based_definition%2Fabout_working_with_mass_property_parameters.html%23)
> * [Specifying the Density of a Part](https://support.ptc.com/help/creo/creo_pma/r7.0/usascii/index.html#page/model-based_definition/specifying_the_density_of_a_part.html)
 
> Which is the description of the `_rotor` and `_stator` `prt`?

I kept the same description for the `_stator` &  `_rotor` as in this other comment above ([#36 Comment](https://github.com/icub-tech-iit/cad-libraries/issues/36#issuecomment-871460000)) which was also the description in the purchase order on WINGST.
> ![image](https://user-images.githubusercontent.com/16266334/123979066-ae878f80-d9c0-11eb-99d8-13c9e214b37a.png)

**Comment by fiorisi** [comment]
@divyashah can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
Let me know if something is not clear.

**Comment by divyashah** [comment]
> @divyashah can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
> Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
> Let me know if something is not clear.

Thanks @fiorisi! 
With this last commit, I updated the mass properties for the TQ motor files as per the new procedure. Now the mass shown in CREO is similar to the rated mass. 
 - TQ_ILM50x08 : ~83g~ **86.99g** (rated mass = 87g)
- TQ_ILM50x14 : ~142g~ **134.99g** (rated mass = 135g)

There is also a small update in the CAD volume and the calculated density that was reported above (due to the addition of the index hole in the rotor): 
> |     Part     |  Measured Mass [kg] | CAD Volume [mm^3] | Calculated Density [kg/mm^3] |
> |:------------:|:---------:|:-------------:|:-----------------:|
> | TQ_ILM50x08_Rotor  |   0.021   |    2692.87    |   7.798 e-6   |
> | TQ_ILM50x08_Stator |   0.066   |    12309.5    |   5.361 e-6   |
> | TQ_ILM50x14_Rotor  |   0.034   |    4385.29    |   7.753 e-6   |
> | TQ_ILM50x14_Stator |   0.101   |    17872.7    |   5.651 e-6   |

Updating this table with correct values now: 

|     Part     |  Measured Mass [kg] | CAD Volume [mm^3] | Calculated Density [kg/mm^3] |
|:------------:|:---------:|:-------------:|:-----------------:|
| TQ_ILM50x08_Rotor  |   0.021   |    2691.69    |   7.802 e-6   |
| TQ_ILM50x08_Stator |   0.066   |    12309.5    |   5.361 e-6   |
| TQ_ILM50x14_Rotor  |   0.034   |    4384.11    |   7.755 e-6   |
| TQ_ILM50x14_Stator |   0.101   |    17872.7    |   5.651 e-6   |

**Comment by fiorisi** [comment]
Great!

@marcellosavoldi do you have time to review the parts and close the issue?

**Comment by fiorisi** [comment]
> @marcellosavoldi do you have time to review the parts and close the issue?

@divyashah probably you can simply add the screenshot of the mass properties as done for the other components (e.g. https://github.com/icub-tech-iit/cad-libraries/issues/45). Then we can close the issue.

**Comment by divyashah** [comment]
> @divyashah probably you can simply add the screenshot of the mass properties as done for the other components (e.g. #45). Then we can close the issue.

Adding the screenshots with mass properties below: 

| **TQ_ILM50X08.ASM**  ~ **87 g** |
|:-----:| 
|![image](https://user-images.githubusercontent.com/16266334/129049643-5796f5e9-144b-4c13-beef-172abd90bbac.png) | 

---

| **TQ_ILM50X14.ASM**  ~ **135 g** |
|:-----:| 
| ![image](https://user-images.githubusercontent.com/16266334/129050062-66e703e9-cc9c-4fc0-805d-fa6b25e52947.png) |

**Comment by fiorisi** [comment]
Great @divyashah. You don't have the radio buttons `Computed` or `Assigned`, correct?

**Comment by divyashah** [comment]
> Great @divyashah. You don't have the radio buttons `Computed` or `Assigned`, correct?

Thanks @fiorisi!
Yes, I don't have those radio buttons anymore. The mass properties are updated as per the [new procedure in the guidelines](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts). 

| TQ_ILM50X08.ASM |
|:------:| 
| ![image](https://user-images.githubusercontent.com/16266334/129054648-a6e234f0-5e59-4418-94a3-f9121c73dbab.png) | 

| TQ_ILM50X14.ASM |
|:------:| 
|  ![image](https://user-images.githubusercontent.com/16266334/129054944-b562936e-3c1e-455e-9b22-e91ea091ad4d.png) |

**Comment by fiorisi** [comment]
@divyashah we need to change the categories of the stator and rotor because Pamoco has 2 different codes.
Can you align with @MrAndrea for this?

**Comment by MrAndrea** [comment]
Yesterday we aligned about the TQ motors, summarising: the motor is combined of two supplier codes, one for rotor and one for stator, and both must be MOT category. On Wingst they have the respectively codes as described in [this comment](https://github.com/icub-tech-iit/ergocub-design-joint/issues/9#issuecomment-961232514).

**Comment by marcellosavoldi** [comment]
> @divyashah we need to change the categories of the stator and rotor because Pamoco has 2 different codes. Can you align with @MrAndrea for this?

We need to discuss how to manage these CAD codes.
We have always used two different models (Stator and Rotor), one of these has the COSM category and the other has the MOTR category ...
Is this case handled differently?
We have never written anything on WIKI, but I think it is worth talking about in the silo meeting and writing a rule.
@fiorisi , @divyashah

**Comment by marcellosavoldi** [comment]
![image](https://user-images.githubusercontent.com/53296021/140501259-82704649-bc03-4c3f-8f92-2e784c7f42f0.png)

**Comment by fiorisi** [comment]
> We have always used two different models (Stator and Rotor), one of these has the COSM category and the other has the MOTR category ...
Is this case handled differently?
We have never written anything on WIKI, but I think it is worth talking about in the silo meeting and writing a rule.

Definitively, we have to discuss it at the next silo meeting and update the WIKI.
For the time being I would keep the `_ROTOR` and `_STATOR`, setting the category `MOTR` for both.
In WINGST we add the correct suppliers code for the 2 parts.

**Comment by divyashah** [comment]
> Yesterday we aligned about the TQ motors, summarising: the motor is combined of two supplier codes, one for rotor and one for stator, and both must be `MOTR` category. On Wingst they have the respectively codes as described in [this comment](https://github.com/icub-tech-iit/ergocub-design-joint/issues/9#issuecomment-961232514).

Thanks @MrAndrea for updating the codes on WINGST.

However, could you please cross check the suppliers codes ?? They don't seem to be correct according to me: 
![image](https://user-images.githubusercontent.com/16266334/140523272-68a3dc7c-c370-4599-92c1-b50cdc01df93.png)

I think the supplier's codes should be as per the [comment in icub-tech-iit/ergocub-design-joint#3](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341).


> For the time being I would keep the `_ROTOR` and `_STATOR`, setting the category `MOTR` for both. 

I will update the categories to `MOTR` for all the components for now. And once we have a decision in the silo-mech meeting, I will update the WIKI accordingly. 

cc @marcellosavoldi @fiorisi

**Comment by MrAndrea** [comment]
Ciao @divyashah, I didn't find the supplier codes that you [mentioned](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341) in any document. Before changing on Wingst, where did you get them?

**Comment by divyashah** [comment]
> Ciao @divyashah, I didn't find the supplier codes that you [mentioned](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341) in any document. Before changing on Wingst, where did you get them?

@MrAndrea I found them in these drawing datasheets: [50x08](https://www.tq-group.com/filedownloads/files/products/robodrive/drawing/drawing_ilm50x08_rev.0102.pdf) and [50x14](https://www.tq-group.com/filedownloads/files/products/robodrive/drawing/drawing_ilm50x14_rev.0101.pdf). (Already added to the internal storage linked in this [comment](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-871541899)). 
In these datasheets they have mentioned all the various configuration codes and the ones [mentioned here](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341) correspond to the motors we bought. I have also verified these codes with the labels on the motors we received.

**Comment by MrAndrea** [comment]
Ok @divyashah they seem to me the manufacturer codes and not the supplier codes, because in the [Pamoco offer](https://github.com/icub-tech-iit/purchases/issues/1042#issuecomment-793990178) there is nothing about them.
So if you agree, I will change both the manufacturer and supplier codes with the same code provided in [your table](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341).

**Comment by divyashah** [comment]
> Ok @divyashah they seem to me the manufacturer codes and not the supplier codes, because in the [Pamoco offer](https://github.com/icub-tech-iit/purchases/issues/1042#issuecomment-793990178) there is nothing about them. 

Yes @MrAndrea you are right. They are the manufacturer codes, and not supplier codes. I got confused between the two. 

> So if you agree, I will change both the manufacturer and supplier codes with the same code provided in [your table](https://github.com/icub-tech-iit/ergocub-design-joint/issues/3#issuecomment-943258341).

Yes, then we can change both codes to the values in the table.

**Comment by divyashah** [comment]
With the previous commit, I modified the rotor category to `MOTR`. 
I also added the new `IIT_CODE` parameter that was recently added to the commercial start_part based on the WINGST codes.

Once the manufacturer's codes have been updated on WINGST, we can close this issue again. 

cc @MrAndrea @fiorisi

**Comment by MrAndrea** [comment]
Manufacturer's codes updated on Wingst.

![image](https://user-images.githubusercontent.com/20459541/140764545-db49d8ba-791b-4dbe-80f9-9a72585ea69f.png)

![image](https://user-images.githubusercontent.com/20459541/140764595-7d549138-a57e-4f20-a863-514096411385.png)

![image](https://user-images.githubusercontent.com/20459541/140764643-5ab5c321-b4e6-4c53-a3a1-e422b11d8ffb.png)

![image](https://user-images.githubusercontent.com/20459541/140764694-9a97af1c-077e-4021-bd01-54755bbda47f.png)

**Comment by fiorisi** [comment]
@MrAndrea @divyashah I think that we can close, right?

**Comment by marcellosavoldi** [comment]
Let's remember to discuss it at the next Silo Mech meeting ...
I think it is useful to reiterate that there are exceptions to entering parameters into the model.
cc: @fiorisi , @icub-tech-iit/silo-mech
