### ISSUE TITLE
[ICYBOX_IB-AC527] - [USB Sound Card Adapter]

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/cad-libraries#39]
| Description | Field |
|:---|:---|
| Datasheet component  | https://www.distrelec.it/Web/Downloads/_t/ds/ib-ac527_eng_tds.pdf |
| project | icub head |
| Alias Creo | ICYBOX_IB-AC527 |
| IIT-Code | 5988  |
| Applicant | @salvi-mattia  |
| supervisor | @fiorisi  |

### Checklist:
- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [ ] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Edited the [parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components).
- [ ] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

#### NOTE
Without these informations is not possible proceed with the request.

**Comment by maggia80** [comment]
@salvi-mattia this component was used in the talking-head we should have already the part

**Comment by salvi-mattia** [comment]
maybe it's similar

![immagine](https://user-images.githubusercontent.com/43994292/124485234-aa86b380-ddac-11eb-812b-49db405646d1.png)

I created this one
https://www.distrelec.it/Web/Downloads/_t/ds/ib-ac527_eng_tds.pdf

**Comment by salvi-mattia** [comment]
according to @pattacini I'm going to use the already existing component reported here above by @maggia80 

I'm not going to commit the new icybox component (cc @fiorisi )

**Comment by fiorisi** [comment]
> according to @pattacini I'm going to use the already existing component reported here above by @maggia80

I'm not going to commit the new icybox component (cc @fiorisi )

**Comment by salvi-mattia** [comment]
> 
> 
> > according to @pattacini I'm going to use the already existing component reported here above by @maggia80
> > I'm not going to commit the new icybox component (cc @fiorisi )
> 
> Great, meanwhile can you please check that the component satisfies the [checklist](https://github.com/icub-tech-iit/cad-libraries/issues/39#issue-937119083)?

DONE

**Comment by fiorisi** [comment]
@salvi-mattia can you check the same issues commenter here https://github.com/icub-tech-iit/cad-libraries/issues/40#issuecomment-875448941?

**Comment by salvi-mattia** [comment]
it's not possible to assign a specifc density to the component due to the problem of materials and bodies seen with @fiorisi 
in the meanwhile I'm going to assign it an existing material with similar mass properties

**Comment by fiorisi** [comment]
@salvi-mattia can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
Let me know if something is not clear.

**Comment by salvi-mattia** [comment]
resolved with eccbe7a60caf917aec284b9cdf9f08fb6fe4cd39

@fiorisi i think we can close, do you agree?

**Comment by fiorisi** [comment]
> @fiorisi i think we can close, do you agree?

Can you just add a screenshot of the mass properties?

**Comment by salvi-mattia** [comment]
![immagine](https://user-images.githubusercontent.com/43994292/128731160-4e45047a-27da-402e-8579-d7752833a7e2.png)
