### ISSUE TITLE
[Intel] - [INTEL_REALSENSE_D450] - [Intel RealSense Camera D450]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#42]
| Description          | Intel Realsense D450, range from 0.52 to 6m, FOV H87 V58 de   |
|:---------------------|:---------------------------------------|
| Datasheet component  |  [Intel-RealSense-D400-Series-Datasheet-June-2020.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6784597/Intel-RealSense-D400-Series-Datasheet-June-2020.pdf), [D450_camera-module_asm_external.zip](https://github.com/icub-tech-iit/cad-libraries/files/6784607/D450_camera-module_asm_external.zip) |
| Project              | ergoCub  |
| Alias Creo           | INTEL_REALSENSE_D450   |
| IIT-Code             | XXXXX                        |
| Applicant            | Michele Gesino, @Mick3Lozzo    |
| Supervisor           | Ugo Pattacini, @pattacini   |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Edited the [parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by Mick3Lozzo** [comment]
*   The item still does not have an IIT-Code
*   Mass properties are uncertain, we have to check when we buy one.

**Comment by fiorisi** [comment]
@Mick3Lozzo can you please edit the issue title?

**Comment by maggia80** [comment]
![image](https://user-images.githubusercontent.com/6987330/125293220-80407300-e323-11eb-8b14-c97bcf81c9bb.png)

and bottom:

![image](https://user-images.githubusercontent.com/6987330/125293281-8c2c3500-e323-11eb-80f1-4605ec3e762e.png)

**Comment by Mick3Lozzo** [comment]
@maggia80 I've found the CAD model of the board. Does it already have a WinGST code?

![](https://user-images.githubusercontent.com/15085666/125422221-6a2ac222-ac5c-4051-a971-0f73f8c92659.png)

**Comment by maggia80** [comment]
to connect the module with the board there are two options:

1. from Intel: a rigid PCB that fix the two parts one over the other more or less like in the picture above. Mouser link https://www.mouser.it/ProductDetail/Intel/82635DSITR50P?qs=wd5RIQLrsJhIJqpBcxiaKQ%3D%3D

2. a flexible PCB with different length provided by FRAMOS: https://www.framos.com/en/hsf50-22273 This option is preferable we should ask for a quotation or if FRAMOS could add these codes in the Mouser catalog. There are already products from FRAMOS available at Mouser. 

There aren't wingst codes for modules and cables

**Comment by fiorisi** [comment]
Great @Mick3Lozzo!

Is it possible to remove all the small features from the [3D model](https://github.com/icub-tech-iit/cad-libraries/issues/42#issuecomment-878903609) so that is lighter to open and render?

**Comment by Mick3Lozzo** [comment]
**D450 weight**: 29,8 g

**Comment by Mick3Lozzo** [comment]
> Is it possible to remove all the small features from the [3D model](https://github.com/icub-tech-iit/cad-libraries/issues/42#issuecomment-878903609) so that is lighter to open and render?

Probably. I imported directly the step file as it was, we could re-import it or work on the already imported part.

**Comment by Mick3Lozzo** [comment]
As already reported by @divyashah [here](https://github.com/icub-tech-iit/cad-libraries/issues/36#issuecomment-874661606) we still have a problem assigning the correct density to commercial components.  
Here, this value should be 0.0000037162 but Creo rounds it up to 0.000004.

![](https://user-images.githubusercontent.com/15085666/125642548-8b7f2e20-a56f-45a2-b496-2830142c113a.png)

So, the overall weight of The RealSense D450 **results in 32 g instead of 29,8 g**.   
For now, there is no solution.  
  
In this case, in percentage is a 7% difference with respect to the real weight but, in absolute terms, it is a really small difference, I think this issue can be closed @fiorisi.

**Comment by Mick3Lozzo** [comment]
[Interposer.zip](https://github.com/icub-tech-iit/cad-libraries/files/6817296/Interposer.zip)

Found an unofficial `step` of the rigid PCB, I'll put it in `cad-libraries`.

**Comment by fiorisi** [comment]
Thanks @Mick3Lozzo.

> think this issue can be closed @fiorisi.

I would not close the issue. We close it once the mass properties are correct.

**Comment by fiorisi** [comment]
@Mick3Lozzo can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
Let me know if something is not clear.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/128478231-7b588e8e-c546-41ec-8b39-d6a76c38abfa.png)

Done: 29,8 g.  
  
cc @fiorisi
