### ISSUE TITLE
Intel - [INTEL_REALSENSE-VISION-D4] - [Intel, RealSense, Vision Processor D4 Board]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#44]
| Description        | Intel® RealSense™ Vision Processor D4     |
|:-------------------|:--------------------------------------|
| Datasheet          | [Intel_RealSense_Vision_Processor_D4_USB_Type_C_V05_PC066105.STEP_.zip](https://github.com/icub-tech-iit/cad-libraries/files/6807634/Intel_RealSense_Vision_Processor_D4_USB_Type_C_V05_PC066105.STEP_.zip), [Intel-RealSense-D400-Series-Datasheet-June-2020.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6807637/Intel-RealSense-D400-Series-Datasheet-June-2020.pdf)  |    
| Project              | ergoCub |
| Manufacturer info  | Intel, RealSense™ Vision Processor D4 |       
| Alias Creo         | INTEL_REALSENSE-VISION-D4         |   
| IIT-Code             | XXXXX       |
| Applicant            | Michele Gesino, @Mick3Lozzo              |
| Supervisor           | Ugo Pattacini, @pattacini            |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |

### Notes:

This is a commercial board, we have still to define how to manage them.

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Edited the [parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by Mick3Lozzo** [comment]
**Board weight**: 4 g.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/125646317-b1532712-bc50-428c-910a-074223eb106f.png)

This is the best result we can obtain, for now, given the known problem with density. 3,7 g.

**Comment by fiorisi** [comment]
I would not close the issue. We close it once the mass properties are correct.

**Comment by fiorisi** [comment]
@Mick3Lozzo can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
Let me know if something is not clear.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/128477114-5baa7efb-d269-4c90-a48a-6826a5031f3e.png)

Done: 4 g  
  
@fiorisi
