### ISSUE TITLE
[Intel] - [Intel_82635DSITR50P] - [Intel, RealSense D400 series, interposer]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#45]
| Description          | Intel RealSense D400 series interposer  |
|:---------------------|:---------------------------------------|
| Datasheet component  |  [Intel_RealSense_D400_Family_Datasheet_Jan2019.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6823591/Intel_RealSense_D400_Family_Datasheet_Jan2019.pdf)  |
| Project              | ergoCub   |
| Alias Creo           | INTEL_82635DSITR50P    |
| IIT-Code             | XXXXX             |
| Applicant            | Michele Gesino, @Mick3Lozzo    |
| Supervisor           | Ugo Pattacini, @pattacini                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |

### Attachment:

[Interposer.zip](https://github.com/icub-tech-iit/cad-libraries/files/6823672/Interposer.zip)

### Notes:

Found an unofficial step file that seems to be really accurate.

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Edited the [parameters](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#parameters-for-commercial-components).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by Mick3Lozzo** [comment]
[Interposer.zip](https://github.com/icub-tech-iit/cad-libraries/files/6823672/Interposer.zip)

Absolutely **unofficial** `step` file.

**Comment by fiorisi** [comment]
@Mick3Lozzo can you please update the mass properties of the part accordingly to the [new procedure](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components)?
Considering that you didn't use the new start part, simply remove the unused parameters, all the materials and follow the suggestions of [this comment](https://github.com/icub-tech-iit/cad-mechanics/issues/152#issuecomment-893291732).
Let me know if something is not clear.

**Comment by Mick3Lozzo** [comment]
According to Intel, the expected weight should be 8 g.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/128842525-26827bd1-a450-48ff-bfd9-a532474baf8c.png)

Done.

**Comment by fiorisi** [comment]
> Done.

Great @Mick3Lozzo.
Can you please add the screenshot of the entire mass properties window?

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/128862876-0c8eb5d0-dd48-4bec-8693-8281777b8a3f.png)
