### ISSUE TITLE
ECAD - [DIODES] - [DXT2011P5 & DXT2012P5] - [NPN and PNP Transistors]

### ISSUE THREAD

**Issue by maurizbo** [icub-tech-iit/cad-libraries#48]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link or attachment ] *               |       |
| Manufacturer info  | [Manufacturer name + serial number] * |       |
| Alias Creo         | [Alias or filename MCAD] \**          |       |
| MCAD Contact       | Marcello Savoldi, @marcellosavoldi                |       |
| ECAD Contact       | Maurizio Borgagni, @maurizbo                |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |
| IITcode | 15453 - 15454|  |
Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

   
![image](https://user-images.githubusercontent.com/53302701/127985443-95f14948-219d-4c8c-ab46-d4c5d06ee2c7.png)

###  Attachments (optional)
I attach here the datasheet related the POWERDI-5 case with all the useful mechanical info
[PowerDI5.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6922746/PowerDI5.pdf)

### Notes (optional)
I created a single request for two component that have differences only in "electronic values" 

### Checklist:
- [x] Added IIT-CODE.
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [ ] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by marcellosavoldi** [comment]
@maurizbo , can you check the issue...
I cant find IIT-CODE and/or datasheets

**Comment by marcellosavoldi** [comment]
![image](https://user-images.githubusercontent.com/53296021/130207486-9373d98d-09b3-4547-8e2d-22dfac5109dc.png)

DONE
