### ISSUE TITLE
[Misumi] - [PACK series] - [Resin Low Head Cap Screws]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#49]
| Description          | Resin Low Head Cap Screws (Generic)  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [P2_0219-0220_F34_IT.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6962192/P2_0219-0220_F34_IT.pdf), [PACK-PEKE3-6_Creo_Parametric_6_20210810.zip](https://github.com/icub-tech-iit/cad-libraries/files/6962194/PACK-PEKE3-6_Creo_Parametric_6_20210810.zip)|             
| Project              | Generic  |
| Alias Creo           | MISUMI_ PACK |
| IIT-Code             | various, for example 15466  |
| Applicant            | Michele Gesino, @Mick3Lozzo         |
| Supervisor           | Marco Maggiali, @maggia80   |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |

### Attachment:

![image](https://user-images.githubusercontent.com/15085666/128882295-04f6db93-68c4-470e-a15b-d9528bf284a1.png)

### Notes:

Family table, including Misumi PACK-RENE, Misumi PACK-PPSE, Misumi PACK-PEKE.

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by marcellosavoldi** [comment]
can you describe better what did you create?
could be interesting an immage and/or a screenshot of the family table for example...
thanks

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/129201841-4b7a092a-5312-4963-bb85-f1274479810c.png)

![](https://user-images.githubusercontent.com/15085666/129206472-4921b0f4-8faa-4aca-95b8-ba42708f02e5.png)

**Comment by marcellosavoldi** [comment]
thanks @Mick3Lozzo ,
I assuming all row signed are good...
only a doubt.... off topic ....  Do we need to buy some tool to use this screws?

other curiosity.... why you didnt use a common cross recessed as following? 
for exemple:
[SPE-M5_P](https://it.misumi-ec.com/vona2/detail/221000233306/?CategorySpec=00000246929%3a%3aa%2cb)
or
[PACK-PPSA](https://it.misumi-ec.com/vona2/detail/110300243360/?CategorySpec=00000246929%3a%3aa%2cb)

the head of these I proposed you, is thinner than your...

**Comment by Mick3Lozzo** [comment]
> the head of these I proposed you, is thinner than your...

Nope. 

![](https://user-images.githubusercontent.com/15085666/129321324-24701b3f-64dd-46c9-b5c2-4b539d212ef2.png)

Mine is **1.5 mm**.

> only a doubt.... off topic .... Do we need to buy some tool to use this screws?

I think a Torx screwdriver should be enough.

![](https://user-images.githubusercontent.com/15085666/129322412-57659b39-bbd0-45d2-9567-3c8c72af0b2a.png)

If we want, this one. I think is similar to a Torx one @marcellosavoldi.

**Comment by marcellosavoldi** [comment]
`If we want, this one. I think is similar to a Torx one @marcellosavoldi. Maybe we already have it in the workshop?`
to be honest I dont know...

**Comment by fiorisi** [comment]
@Mick3Lozzo how did you set the material properties?

**Comment by Mick3Lozzo** [comment]
> [**@Mick3Lozzo**](https://github.com/Mick3Lozzo) how did you set the material properties?

For now, I've set PP, (Polypropylene). The correct material should be PPS (Polyphenilene Sulfide).  
  
[Here](https://www.makeitfrom.com/compare/Polyphenylene-Sulfide-PPS/Polypropylene-PP-Homopolymer) I found a comparison between the two materials.  
  
 

![](https://user-images.githubusercontent.com/15085666/132214854-797ce9e2-941a-4722-9d42-26f0b062bb72.png)

![](https://user-images.githubusercontent.com/15085666/132214898-97519be5-3d4b-426d-8b5d-f7a945bd8b97.png)

The density is really similar, if we think is better, we could think to prepare a proper \*.mtl file.  
  
Today I have tried them, and the mounting tool we have in the workshop works.

![](https://user-images.githubusercontent.com/15085666/132215264-0ce8bd82-3123-49cb-bf33-17482ff2c791.png)

cc @icub-tech-iit/silo-mech

**Comment by fiorisi** [comment]
> For now, I've set PP, (Polypropylene). The correct material should be PPS (Polyphenilene Sulfide).

@Mick3Lozzo please do not invent yet another method to set the material for commercial parts. We have a standard way documented in the guidelines, can you stick to it? 🙂

**Comment by Mick3Lozzo** [comment]
@fiorisim yep, but this is a screw part of a family table, If we set the correct \*.mtl file it will work for all instances.

**Comment by Mick3Lozzo** [comment]
Created and assigned `pps` material file, density set to 1.7^10-6 kg/mm3, the weight of a single screw results to be 0,4 g.

**Comment by fiorisi** [comment]
> Created and assigned pps material file, density set to 1.7^10-6 kg/mm3, the weight of a single screw results to be 0,41 g.

@Mick3Lozzo I would not create a new material. Creating a material is not only about the density, there are many other parameters that must be set correctly.

Please follow the standard procedure for commercial components. If you want to change the procedure please add a point to the next @icub-tech-iit/silo-mech meeting. 
Until then please **always** follow the guidelines, do not create new way of doing things. 🙂

**Comment by Mick3Lozzo** [comment]
@fiorisi done. And added a point to the next silo meeting.

**Comment by fiorisi** [comment]
> @fiorisi done. And added a point to the next silo meeting.

Great. I let the maintainer @marcellosavoldi review and close the issue.

**Comment by marcellosavoldi** [comment]
I am not able to understand that it was saved with the right license, so i trust it.
otherwise ok.
@Mick3Lozzo , you can close.
