### ISSUE TITLE
ECAD - [LSM6DSL] - [12629] - [iNEMO inertial module]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#51]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | [link or attachment ] *               |    [ST MICROELECTRONICS - iNEMO inertial module LSM6DSL.pdf](https://github.com/icub-tech-iit/cad-libraries/files/6974098/ST.MICROELECTRONICS.-.iNEMO.inertial.module.LSM6DSL.pdf)   |
| Manufacturer info  | [Manufacturer name + serial number] * |    St microelectronics - LSM6DSLTR   |
| Alias Creo         | [Alias or filename MCAD] \**          |   LSM6DSLTR    |
| MCAD Contact       | Name Surname, @username               |    @Lawproto    |
| ECAD Contact       | Name Surname, @username               |    @fgarini    |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |   @marcellosavoldi     |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)

@fgarini , please added the immage of PIN1 here.... ask to @maurizbo 

### Plug connector information (mandatory for connectors "board to wire")

no required

### Checklist:
- [x] Added IIT-CODE.
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [ ] Added details about the PLUG connector (added datasheet, or Wingst code).
- [x] Converted the files with the [EDU-COM license](https://www.ptc.com/en/support/article/CS33072).

**Comment by fgarini** [comment]
![image](https://user-images.githubusercontent.com/84333807/129172250-d4c88b4b-3af6-484b-afb6-403686935537.png)
Decal from Pads layout

**Comment by Lawproto** [comment]
@fgarini from your image I get this:

![image](https://user-images.githubusercontent.com/84333301/129183480-1b7fd351-e249-4571-be0a-37a371c37e91.png)

Is it correct?

**Comment by fgarini** [comment]
> @fgarini from your image I get this:
> 
>
> 
> Is it correct?

yes it is centered

**Comment by Lawproto** [comment]
Just as a note, I found this [cool website](https://www.ultralibrarian.com/) for downloading CAD 3D models for electronic components, both in a mechanical format (STEP) and in a electronical format. (Orcad, Altium, Pads... you name it!)
This is what ST Microelectronics itself uses as a 3D database for its own stuff.

**Comment by simeonedussoni** [comment]
here the rules for the land pattern of LGA package

![immagine](https://user-images.githubusercontent.com/31098248/129199271-275174a1-682c-41b3-be68-044585e5f4e6.png)


snapshot is taken from this [ST Technical note](https://www.st.com/resource/en/technical_note/tn0018-surface-mounting-guidelines-for-mems-sensors--in-an-lga-package--stmicroelectronics.pdf)

**Comment by marcellosavoldi** [comment]
sorry @Lawproto ,
can you check the following things?
- I noted in the parts all parameters are missing, same for the relation.
- The mass proprieties are not right.... 
- the unit are in MM Newton Second  and not mm Kg Sec
- the footprint must be above the part , it is not valid to trace it :stuck_out_tongue_winking_eye: ... you have to create it from datasheet , we use it as a check
I noted little discrepancy on the dimensions.
Remember you have to create the model using the maximum tollerances you find in the datasheet ( in this case 2.6x3.1).

![image](https://user-images.githubusercontent.com/53296021/129220673-4464cc2c-6e0d-4f07-a269-009b29539b99.png)
![image](https://user-images.githubusercontent.com/53296021/129220710-310a11ce-61e8-4628-bf63-47cd8f0f6287.png)
![image](https://user-images.githubusercontent.com/53296021/129220776-c5cd5483-51e6-4620-bd9b-69f799d13f73.png)
![image](https://user-images.githubusercontent.com/53296021/129220968-09e36667-32fe-4974-bc2c-7e5a8709e0af.png)

**Comment by marcellosavoldi** [comment]
No @Lawproto , it's very important have a maximum dimensions in the cad-libraries parts ( the same happen for the PADS libraries parts )
The best better to proceed is "import" the step file in a new parts , not open directly the step file, this can solve many things for you.
All our components are done in this way.
if you are convinced otherwise, we can discuss it.

**Comment by Lawproto** [comment]
The alias here - `LSM6DSLTR` - does not match with the alias in _WinGST_:
![image](https://user-images.githubusercontent.com/84333301/129316862-c0127787-e40a-4b41-8e16-3eba480f4fea.png)

@fgarini which is the correct one?

**Comment by Lawproto** [comment]
@marcellosavoldi I am trying to recreate the footprint without referencing the 3D model, as you suggested. I am having trouble finding a `y-axis` reference in the datasheet for the three pins group, though:

![image](https://user-images.githubusercontent.com/84333301/129321243-d8c1b3e7-43ba-4540-9bb4-8faf7d2c134a.png)

What should we do in cases like this?

**Comment by maurizbo** [comment]
Hi @Lawproto alias  sometimes is related to the P/N some times not, for example capacitor are 

CAP-0402-X7R-100NF-16V-10TOL

sometimes related to the P/N 

The important thing is that it is unique for each P/N in our lib and it is correctly linked

**Comment by maurizbo** [comment]
@Lawproto,  anyway due to the fact that this component is not used yet on our boards I will change the alias according with the P/N to avoid future misunderstandic
 from LSM6DSL to LSM6DSL to LSM6DSL**TR**

**Comment by marcellosavoldi** [comment]
> @marcellosavoldi I am trying to recreate the footprint without referencing the 3D model, as you suggested. I am having trouble finding a `y-axis` reference in the datasheet for the three pins group, though:
> 
> ![image](https://user-images.githubusercontent.com/84333301/129321243-d8c1b3e7-43ba-4540-9bb4-8faf7d2c134a.png)
> 
> What should we do in cases like this?

I suppose 0.1...
![image](https://user-images.githubusercontent.com/53296021/129324965-0a35c3e2-2744-4852-a586-03bdd272041d.png)

**Comment by marcellosavoldi** [comment]
> La [wiki](https://github.com/icub-tech-iit/mechatronics/wiki/How-to-create-a-library-component-in-Creo-Parametric) ti invita a scaricare il modello il modello ma non menziona affatto le tolleranze massime.
> 
> Se questo aspetto è così importante, il wiki dovrebbe essere modificato di conseguenza. Tuttavia, in questo modo stiamo fortemente ostacolando la comodità di avere la geometria 3D direttamente dal sito del produttore per un vantaggio troppo piccolo in cambio, secondo me.
> 
> Capisco il ragionamento alla base di questo, ma anche per i componenti meccanici - se ci pensi - la stragrande maggioranza delle dimensioni 3D sono modellate da rappresentano il valore centrale del loro intervallo di tolleranza (vedi tolleranze ISO generali). Perché utilizzare un approccio diverso in questo caso?
> 
> Quindi, sono ancora per utilizzare i 3D del fornitore così come sono, se possibile.
> 
> Qual è la tolleranza che abbiamo per i componenti posizionati in un PCB e le dimensioni del PCB, comunque?

I think is better open an issue for this...
could be interesting deepen the discussion.
In any case I think is very important for the component keep the maximum dimensions...

**Comment by fiorisi** [comment]
> I think is better open an issue for this...

Yes, I agree. We can open an issue to collect all the comments/ideas on the procedure. 
Then next week we can organize a call to review the comments.

**Comment by Lawproto** [comment]
I will open an issue with my comments ASAP.
@fiorisi @marcellosavoldi

**Comment by fiorisi** [comment]
@Lawproto can you check also the missing boxes before closing the issue?

![image](https://user-images.githubusercontent.com/8970230/129339285-3ae5c360-d3b4-430f-99c5-9d9930653a4e.png)

**Comment by Lawproto** [comment]
@fiorisi OK.

1. `Added details about PLUG connector` seems not proper for this component - it is not a connector. Should I check it, anyway?
1. I am not sure about `Converted the files with the EDU-COM license`'s meaning. Can you help me?

**Comment by marcellosavoldi** [comment]
> @fiorisi OK.
> 
> 1. `Added details about PLUG connector` seems not proper for this component - it is not a connector. Should I check it, anyway?

No, you can miss it

> 2. I am not sure about `Converted the files with the EDU-COM license`'s meaning. Can you help me?

![image](https://user-images.githubusercontent.com/53296021/129540091-26627ad1-6cfa-417a-baa6-dacb09e89b5a.png)
![image](https://user-images.githubusercontent.com/53296021/129540219-ab29c985-8850-4c97-b031-38eb09924500.png)
![image](https://user-images.githubusercontent.com/53296021/129542292-e498badb-ecb5-4b14-be6a-0df127ffc9c6.png)

Now save the part and remember to unsign the licences EDU_Com Convert after saving.

**Comment by fiorisi** [comment]
Thanks @marcellosavoldi. I've copied the images in a dedicated [guide](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

I will also update the issue templates to point the guide.
