### ISSUE TITLE
[WIKI] - [draft proposal for WIKI : vademecum]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#52]
I think it may be useful to create a page in the WIKI on cad-libraries, where we indicate the standard screws we use for our assemblies and how to search for them in cad-libraries.
For exemple:
- Use pozidrive ISO7045 screws and Philips ISO7046 screws
- For screws greater than M3 it is preferable to use UNI5931 and 5933 etc ...
- For sheet metal parts use following PEM nut...
- For plastic use following helicoils : ..... or following nuts PMS-Celada: .....
- family table of bearing : ....( see for example [here](https://github.com/icub-tech-iit/cad-mechanics/issues/13) )
- etc...

I want keep this issue to create a DRAFT page to propose a new page in a WIKI.
for now I dont need comments for this issue , let you know in due course when I finished the proposal issue to validate it

**Comment by fiorisi** [comment]
@marcellosavoldi please edit directly the wiki without opening an issue.
