### ISSUE TITLE
SEEGER - SW-25 - Snap ring type SW for shafts

### ISSUE THREAD

**Issue by divyashah** [icub-tech-iit/cad-libraries#56]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [SW rings for shaft](https://www.seeger-orbis.com/products/snap-rings/circlips/snap-rings/circlips-to-din-9927-9928)                  |
| Project              | Generic    |
| Alias Creo           | SEEGER_SW-25                       |
| IIT-Code             |                       |
| Applicant            | Divya Shah, @divyashah                |
| Supervisor           | Luca Fiorio, @fiorisi                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers     | @icub-tech-iit/silo-mech           |

### Attachment:
[Seeger_SW_Datasheet.pdf](https://github.com/icub-tech-iit/cad-libraries/files/7099781/datenblatt_seeger-ringe_Sprengringe_Wellen.pdf)

### Notes:
For the new ergoCub joint, I am using the **SEEGER_SW-25** snap ring for shaft. So I would like to add it to the library. Here is a CAD render of the component. 
![image](https://user-images.githubusercontent.com/16266334/131868013-3ad856b3-02be-4616-8d10-dc92d09f41b2.png)

However, we can consider creating a **family table** of this category of snap rings, since this is missing. 

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by fiorisi** [comment]
@divyashah concerning the alias of these parts I would not use SEEGER_xxx.
For this kind of fasteners (like screws and bolts) we use the technical specification standard. We have to check the one that defines this components and if available in more than one decide which use.
I've opened a [dedicated page](https://github.com/icub-tech-iit/cad-mechanics/wiki/Technical-specification-standards).

**Comment by marcellosavoldi** [comment]
in the past we looking for new componets in this [folder](https://istitutoitalianotecnologia.sharepoint.com/:f:/r/sites/icub-facility/Documenti%20condivisi/Silo%20Mechanics/sandbox/proe___librerie_compass?csf=1&web=1&e=2b1AMH) ...
Don't ask me where these documents come from because I don't remember

**Comment by divyashah** [comment]
> @divyashah concerning the alias of these parts I would not use SEEGER_xxx.
> For this kind of fasteners (like screws and bolts) we use the technical specification standard. We have to check the one that defines this components and if available in more than one decide which use.
> I've opened a [dedicated page](https://github.com/icub-tech-iit/cad-mechanics/wiki/Technical-specification-standards).

I am using the `SW` type of the Seeger Ring as mentioned in the description. On the Seeger Rings website, the standard mentioned for this type of rings is **DIN 9927**. 

However, this type of elastic ring is not mentioned among the brochures that are linked in the technical standard specification page on the wiki referenced above. 

> in the past we looking for new componets in this [folder](https://istitutoitalianotecnologia.sharepoint.com/:f:/r/sites/icub-facility/Documenti%20condivisi/Silo%20Mechanics/sandbox/proe___librerie_compass?csf=1&web=1&e=2b1AMH) ...

Also, from the files present in this sharepoint folder, the ring similar to one I am using is named `NOR_INA_WR.PRT` which doesn't have any particular standard code (ISO/UNI/DIN). 

We need to ensure if this is actually a standard ring or not. We can then define the alias accordingly. 

cc @marcellosavoldi @fiorisi

**Comment by fiorisi** [comment]
@divyashah can we close the issue following the approved [technical standards](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#technical-standards)?

**Comment by divyashah** [comment]
> @divyashah can we close the issue following the approved [technical standards](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#technical-standards)?

@fiorisi I still did not commit the file for the this. I have created the family table, but I wanted to check if I can somehow assign the calculated density, for every instance, as a relation.

I will try it and then commit the files accordingly, before closing this.

**Comment by marcellosavoldi** [comment]
since we're talking about an object made of a material ... can we just assign a 308 stainless steel and let Creo do it all?

@fiorisi , @divyashah

**Comment by fiorisi** [comment]
> since we're talking about an object made of a material ... can we just assign a 308 stainless steel and let Creo do it all?

If the datasheet of the component specifies that is made of that material, then yes.
Otherwise I would wait to have the new materials library and discuss weather introducing some generic materials to use for these cases.

**Comment by MrAndrea** [comment]
It will be useful to discuss this task at the next Silo Meeting at the of the month.

**Comment by divyashah** [comment]
I added the `DIN_9927.PRT` family table for the SEEGER ring type **SW** for shafts. 
![image](https://user-images.githubusercontent.com/16266334/173819441-5e67aff8-8f24-4da4-9333-f003f3ea3196.png)


For now, the family table consists of instances from nominal diameter 14 mm to 47 mm. 
![image](https://user-images.githubusercontent.com/16266334/173819257-7d2683d2-333b-4c2c-80ca-4ef6392343b2.png)


I also assigned calculated density for each instance following the solution proposed in https://github.com/icub-tech-iit/cad-mechanics/issues/214#issuecomment-1155507804.
