### ISSUE TITLE
Editing [NVIDIA_JETSON_AGX_XAVIER_HS_CB]-[updating mass properties]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#59]
| Description   | Jetson AGX Xavier with heatsink and carrier board      |
|:--------------|:-----------------------------------|
| Category      | [ECAD-MCAD]                        |
| Alias Creo    | NVIDIA_JETSON_AGX_XAVIER_HS_CB    |
| IIT-Code      | 14615, 14616, 14617  |
| Applicant     | Michele Gesino, @Mick3Lozzo    |
| Supervisor    | Ugo Pattacini, @pattacini     |
| Maintainer    | Marcello Savoldi, @marcellosavoldi |
| Coworkers     | @icub-tech-iit/silo-mech           |

## Description and motivation of the changing request: <br>
Updating mass properties, following the defined procedure.

## Checklist:
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by Mick3Lozzo** [comment]
Ask @emilianob80 to weigh the only assembled group we have in IIT, at the moment mounted on an R1 robot.

![](https://user-images.githubusercontent.com/15085666/132883609-07abe0bf-41b5-441c-8faf-742ce5f4d2a7.png)

**Comment by Mick3Lozzo** [comment]
Opened [ticket](https://github.com/icub-tech-iit/tickets/issues/1634).

**Comment by fiorisi** [comment]
> Opened ticket.

@Mick3Lozzo please document here the picture of the weight scale with the component.

**Comment by emilianob80** [comment]
> > Opened ticket.
> 
> @Mick3Lozzo please document here the picture of the weight scale with the component.

@Mick3Lozzo @fiorisi  sorry it is my fault that due to lack of time I was unable to satisfy the open ticket. Tomorrow morning I will carry out the weight if the robot is available

**Comment by Fabrizio69** [comment]
Sorry @Mick3Lozzo , if you need of the PROTO-Team support, mention me too. Thanks

cc: @emilianob80 @fiorisi

**Comment by pattacini** [comment]
Yes, it's important to keep the SM in the loop.

**Comment by emilianob80** [comment]
@Mick3Lozzo the robot is connected and completely switched on (PC and motors) so it is not possible for me to remove the cards and carry out the weighing

cc: @Fabrizio69 @pattacini @fiorisi

**Comment by pattacini** [comment]
I went down to check the system and I just found the SN003 on and plugged into the power supply. There's no console around.
@randaz81, @datspace @lnobile, can we power it off using the switches as it is?

As it's written here, we'd need to temporarily unmount/mount the NVIDIA board to measure the actual weight.

**Comment by DatSpace** [comment]
Yes certainly. Everything is saved and the robot is not running anything really. It was simply recommended to not be killed to increase the lifespan of the electronics.

**Comment by lnobile** [comment]
Yeah no problem also for me! Will the robot be available tomorrow? (With the NVIDIA board mounted)

**Comment by pattacini** [comment]
Thanks heaps guys 👍🏻 
So, @emilianob80, we can proceed by switching off the robot as it is.
Please, just coordinate w/ @lnobile to address his request below and agree on when it's the right moment.

>Will the robot be available tomorrow? (With the NVIDIA board mounted)

**Comment by emilianob80** [comment]
@lnobile @pattacini the robot is available again. Thanks

cc: @Fabrizio69 @DatSpace @randaz81

**Comment by pattacini** [comment]
Super 🚀

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/134477190-7598adcf-c737-4588-89c8-83e14f04bc80.png)

![](https://user-images.githubusercontent.com/15085666/134477254-31d1bf65-28e0-4719-b6e8-c5ad665811e7.png)

Updated density and corrected mass.

**Comment by Mick3Lozzo** [comment]
Converted with EDU-COM license. I'll close the issue.
