### ISSUE TITLE
[RLS] - [MRA7D049AB025E00] - [Magnetic wheel for AksIM encoder]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#61]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [website](https://www.rls.si/eng/aksim-rotary-absolute-encoder-module )            |
| Project              | ergoCub     |
| Alias Creo           | rls_MRA7D049AB025E00                        |
| IIT-Code             | 11259                       |
| Applicant            | Marcello Savoldi, @marcellosavoldi                |
| Supervisor           | Luca Fiorio, @fiorisi               |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [ ] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [ ] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [ ] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
dimensions:
![image](https://user-images.githubusercontent.com/53296021/134197116-44471dc3-f0ee-49e7-9a61-fd371060dac9.png)
![image](https://user-images.githubusercontent.com/53296021/134197192-65c716f2-65c0-48a4-93d8-26d7177496fd.png)

**Comment by divyashah** [comment]
For the ergoCub joint we previously discussed about the encoders to use in icub-tech-iit/ergocub-design-joint#7.  

As mentioned by @MrAndrea, it was decided to use AksIM-2 with the following two magnetic rings:  
> `MRA049BC025DSE00` with Countersunk fasteners
> `MRA049BG034DSN00` with Glue

The corresponding purchase request is icub-tech-iit/purchases#1307. 



> I'm going to create a family table where I'll add all variant we'll need.

@marcellosavoldi  if you are creating a family table of these magnetic rings, then I think it would be useful to add also these two configurations, `MRA049BC025DSE00` and `MRA049BG034DSN00`.

**Comment by marcellosavoldi** [comment]
I proceed to add in the family table the following encoders:
![image](https://user-images.githubusercontent.com/53296021/134306271-7f2a8b33-2cdc-44be-85e1-d7b78b8d4d84.png)
![image](https://user-images.githubusercontent.com/53296021/134306346-9128abf5-25ea-48b4-b429-b509b494bbd2.png)
![image](https://user-images.githubusercontent.com/53296021/134308961-7582559a-edb4-4cb1-8641-dafda83d9da2.png)

**Comment by fiorisi** [comment]
@marcellosavoldi once the [checklist](https://github.com/icub-tech-iit/cad-libraries/issues/61#issue-1002654124) has been completed can we close this issue?

**Comment by marcellosavoldi** [comment]
we decided to not use a family table creating the parts.
we can close

**Comment by fiorisi** [comment]
> we decided to not use a family table creating the parts. we can close

Thanks, can you just complete the [checklist](https://github.com/icub-tech-iit/cad-libraries/issues/61#issue-1002654124)?
