### ISSUE TITLE
Editing [HFUC-5-50-2A-R-SP_A]-[updating mass]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#63]
| Description   | Harmonic drive - Gearbox, size 5, gear ratio 50  |
|:--------------|:-----------------------------------|
| Category      | [ECAD-MCAD]                        |
| Alias Creo    | HFUC-5-50-2A-R-SP_A, HFUC-5-50-2A-R-SP_B, HFUC-5-50-2A-R-SP_C   |
| IIT-Code      | 2708.1       |
| Applicant     | Michele Gesino, @Mick3Lozzo         |
| Supervisor    | Ugo Pattacini, @pattacini    |
| Maintainer    | Marcello Savoldi, @marcellosavoldi |
| Coworkers     | @icub-tech-iit/silo-mech           |

## Description and motivation of the changing request: <be>

I have found a mistake in the  HFUC-5-50-2A-R-SP harmonic drive's mass of 36 g but, according to the datasheet, it should be 9 g.

![image](https://user-images.githubusercontent.com/15085666/135233121-b4e4e06f-98fe-466f-8d26-da8c94a34805.png)

![image](https://user-images.githubusercontent.com/15085666/135233142-ba618aeb-f15a-418d-8196-dc2d63e19e57.png)

## Checklist:
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/135235398-35f0bcd2-20d3-489d-ab1b-0048b9ae3d58.png)

Ok, the problem was the wave generator, its density had ten times the expected value.

**Comment by Mick3Lozzo** [comment]
Done.

**Comment by marcellosavoldi** [comment]
If the part is ok, @Mick3Lozzo you can close and push the prt!
