### ISSUE TITLE
[Slamtec] - [RPLIDAR_USB_ADAPTER] - [RPLidar USB Adapter Board for A2/A3]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#64]
| Description          | Slamtec RPLidar USB Adapter Board for A2/A3  |
|:---------------------|:---------------------------------------|
| Datasheet component  |   [LM310_SLAMTEC_rplidarkit_usermanual_A3M1_v1.0_en.pdf](https://github.com/icub-tech-iit/cad-libraries/files/7276064/LM310_SLAMTEC_rplidarkit_usermanual_A3M1_v1.0_en.pdf) |
| Project              | R1, ergoCub    |
| Alias Creo           | SLAMTEC_RPLIDAR-RB-RPK-10     |
| IIT-Code             | ---                   |
| Applicant            | Michele Gesino, @Mick3Lozzo                 |
| Supervisor           | Marco Maggiali, @maggia80      |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Notes:

Bought inside the kit of `11404 -SLAMTEC_RPLIDAR-A2M4-R1`.

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/135275860-34cb6924-3850-4e7a-add0-eea5bc660938.png)

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/135276434-b8ca9b7b-2947-416e-9023-7899c899d4cd.png)

**Comment by fiorisi** [comment]
@Mick3Lozzo the manufacturer doesn't have a code for this product? 
Or `RPLIDAR-ADAPTER-A2-A3` is the manufacturer code?

If we don't know, could be worth to send an email to retrieve it.

**Comment by Mick3Lozzo** [comment]
@fiorisi I haven't found anything more specific on the website, we can ask.

**Comment by Mick3Lozzo** [comment]
Found

![](https://user-images.githubusercontent.com/15085666/135457092-1dbc0afe-a3d4-422b-95ef-75b6b6b6e81a.png)

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/135457797-e6165713-0e45-4084-baf0-737aa1138a20.png)

.... well, technically we should rename ALL RPLidar items we are using in the assemblies.

**Comment by fiorisi** [comment]
Great!

Why do you keep `RPLIDAR` ? Is not part off the product code. If we stick to the [guidelines](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard) we shouldn't include it, right?

**Comment by Mick3Lozzo** [comment]
> Why do you keep `RPLIDAR`? Is not part of the product code. If we stick to the [guidelines](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard) we shouldn't include it, right?

With other members of this product family, we didn't use the reseller code at all but there is a reason: on the [official product page](https://www.slamtec.com/en/Lidar/A3) of Slamtec there doesn't seem to be mention of the USB adapter as a single product - or at least I haven't found it. 
In every other component of the RPLIDAR family, we didn't use this reseller product code because we found a corresponding code on the Slamtec website. 

![image](https://user-images.githubusercontent.com/15085666/135809632-c0538abc-a00e-48e4-aa8e-c4129c94665f.png)

It is mentioned in the attached pdf manual, but it doesn't seem to have a specific code, it is only called "RPLIDAR Adapter". Moreover, according to the manufacturer website, it **seems** this item can be purchased only as a part of a development kit. The reseller Roboshop, instead, allows you to buy it separately.

So, the choice in my opinion could between these two codes:

- `SLAMTEC_RPLIDAR-ADAPTER-A2-A3` (the previous one)
- `SLAMTEC_RB-RPK-10`

@fiorisi

**Comment by marcellosavoldi** [comment]
I would propose to use the name of the company that sells the item.
As I seem to have understood that Samtec does not sell this item individually ...
