### ISSUE TITLE
Editing [SLAMTEC_RPLIDAR-A2M4-R1]-[correcting mass]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#65]
| Description   | Field                              |
|:--------------|:-----------------------------------|
| Category      | [ECAD-MCAD]                        |
| Alias Creo    | SLAMTEC_RPLIDAR-A2M4-R1                |
| IIT-Code      | 11404                  |
| Applicant     | Michele Gesino, @Mick3Lozzo             |
| Supervisor    | Marco Maggiali, @maggia80    |
| Maintainer    | Marcello Savoldi, @marcellosavoldi |
| Coworkers     | @icub-tech-iit/silo-mech           |

## Description and motivation of the changing request: <br>
Correcting the mass value, it should be 199 g.

## Checklist:
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/135463368-f4c8dcce-fd45-4e2c-b835-a2352bf84579.png)

Done.

**Comment by Mick3Lozzo** [comment]
Note: 199 g is a value obtained by weighting a `15507 -SLAMTEC_RPLIDAR-A3M1` model, I expect that there is no significant difference, but we should verify.

**Comment by fiorisi** [comment]
Gentle reminder for @Mick3Lozzo.

**Comment by Mick3Lozzo** [comment]
![](https://user-images.githubusercontent.com/15085666/145425313-43f808f5-9d6a-45fd-8bfc-eba8f1577b12.png)

![](https://user-images.githubusercontent.com/15085666/145425711-62811aa3-8597-4d29-bcd3-be7fb6f36dc4.png)

@fiorisi on the website, RPLIDAR is used only with some components, I would consider it as part of the component's name.

**Comment by fiorisi** [comment]
In the [datasheet](https://bucket-download.slamtec.com/bd39cf1da6f2c64fdb178440106561dc9fc0aa6d/LD310_SLAMTEC_rplidar_datasheet_A3M1_v1.9_en.pdf) of this component there is written `A3M1`. I think that `RPLIDAR` is the series. If you already used the part in many assemblies then we we can avoid the renaming.

![image](https://user-images.githubusercontent.com/8970230/145575976-ae48c628-e9e7-4cd4-9f42-7f3f8be801d5.png)

**Comment by Mick3Lozzo** [comment]
@fiiorisi  already used It only in the ergoCub head, but there are other RPLIDAR models in the various R1 versions.

![](https://user-images.githubusercontent.com/15085666/145782077-b26170c7-20ea-4a45-ac8f-22e91d36a9ef.png)

.... and they have `RPLIDAR` in the filename.

**Comment by fiorisi** [comment]
> @fiiorisi  already used It only in the ergoCub head, but there are other RPLIDAR models in the various R1 versions.

This is work done before the new guidelines and we do not modify it.

**Comment by Mick3Lozzo** [comment]
@fiorisi errata corrige: this is an **OLD** component too, and is present in R1 assemblies, added before the new guidelines.

The new RPLIDAR used in ergoCub head is the `SLAMTEC_RPLIDAR_A3M1`, which I could rename in `SLAMTEC_A3M1`.
