### ISSUE TITLE
NVIDIA - jetson agx xavier- [short description]

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/cad-libraries#69]
| Description          |NVIDIA - jetson agx xavier                          |
|:---------------------|:---------------------------------------|
| Datasheet component  | https://developer.nvidia.com/embedded/jetson-agx-xavier-developer-kit            |
| Project              | ergocub et al    |
| Alias Creo           | NVIDIA_JETSON_AGX_XAVIER                        |
| IIT-Code             | 14617                     |
| Applicant            | @salvi-mattia            |
| Supervisor           | @pattacini               |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

![immagine](https://user-images.githubusercontent.com/43994292/138068078-d80a48b6-5f6c-4ac3-825d-4b2cf44f9bd4.png)

### Notes:
I didn't find weight in any datasheet, just on [this](https://forums.developer.nvidia.com/t/weigth-of-jetson-agx-xavier-module-only/71381) forum.

PLEASE DO NOT CLOSE THIS ISSUE BEFORE CHECKING THE WEIGHT ON A SCALE

### Checklist:
Complete the checklist in order to proceed with the request.

- [X] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [X] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [X] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by fiorisi** [comment]
@salvi-mattia great.
Please just align the code accordingly with [the guidelines](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard). Then we can close.

**Comment by fiorisi** [comment]
> @salvi-mattia great.
Please just align the code accordingly with the guidelines. Then we can close.

Gentle reminder for @salvi-mattia.

**Comment by fiorisi** [comment]
@salvi-mattia can we close this issue?

**Comment by salvi-mattia** [comment]
no,
ther is still the pending decision if you want to change the name even if it is used somewhere
[is it really used somewhere?]
