### ISSUE TITLE
connecttech - Xavier Passive Heat Sink - NVIDIA Jetson AGX Xavier Passive Heat Sink

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/cad-libraries#70]
| Description          |NVIDIA Jetson AGX Xavier Passive Heat Sink                             |
|:---------------------|:---------------------------------------|
| Datasheet component  | https://connecttech.com/product/nvidia-jetson-agx-xavier-passive-heat-sink/                |
| Project              | ergocub and more   |
| Alias Creo           | CONNECTTECH_AGX_PASSIVE_HS                        |
| IIT-Code             | 15529                       |
| Applicant            | @salvi-mattia               |
| Supervisor           | @pattacini            |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
![immagine](https://user-images.githubusercontent.com/43994292/138101195-e6b05be4-9a41-432b-b08e-b0c68fd19dad.png)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by fiorisi** [comment]
@salvi-mattia can you check the alias as per https://github.com/icub-tech-iit/cad-libraries/issues/71#issuecomment-986600107?

**Comment by fiorisi** [comment]
> @salvi-mattia can you check the alias as per #71 (comment)?

Gentle reminder for @salvi-mattia.

**Comment by fiorisi** [comment]
@salvi-mattia can we close this issue?

**Comment by salvi-mattia** [comment]
no,
ther is still the pending decision if you want to change the name even if it is used somewhere
[is it really used somewhere?]

**Comment by fiorisi** [comment]
> no, ther is still the pending decision if you want to change the name even if it is used somewhere [is it really used somewhere?]

No, as agreed during the last silo meeting we do not rename parts.
If all the other points are satisfied feel free to close the issue.
