### ISSUE TITLE
connecttech - Xavier Active Heat Sink - NVIDIA Jetson AGX Xavier Active Heat Sink

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/cad-libraries#71]
| Description          | NVIDIA Jetson AGX Xavier Active Heat Sink|
|:---------------------|:---------------------------------------|
| Datasheet component  |https://connecttech.com/product/nvidia-jetson-agx-xavier-active-heat-sink/               |
| Project              | ergocub et al   |
| Alias Creo           | CONNECTTECH_AGX_ACTIVE_HS                       |
| IIT-Code             | 14616                        |
| Applicant            | @salvi-mattia              |
| Supervisor           | @pattacini                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

![immagine](https://user-images.githubusercontent.com/43994292/138422863-40dcf96f-f21b-4547-9cc4-98dbd913495f.png)

![immagine](https://user-images.githubusercontent.com/43994292/138423669-20646fe0-0b0a-4ec4-8c46-35d5f41b3f3a.png)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by fiorisi** [comment]
@salvi-mattia can you check in the ordering information the product code?
![image](https://user-images.githubusercontent.com/8970230/144822161-31f0a1d9-ad75-4363-9e69-fe1a72cd692c.png)

Furthermore, the spaces in the code shall be replaced with `-`.
See https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard
![image](https://user-images.githubusercontent.com/8970230/144822665-0ebd0e61-8313-4b7f-bbc7-54ef4d5dd75e.png)

**Comment by fiorisi** [comment]
> See comment: https://github.com/icub-tech-iit/cad-libraries/issues/71#issuecomment-986600107

Gentle reminder for @salvi-mattia.

**Comment by fiorisi** [comment]
@salvi-mattia can we close this issue?

**Comment by salvi-mattia** [comment]
no,
ther is still the pending decision if you want to change the name even if it is used somewhere
[is it really used somewhere?]

**Comment by fiorisi** [comment]
> no, ther is still the pending decision if you want to change the name even if it is used somewhere [is it really used somewhere?]

No, as agreed during the last silo meeting we do not rename parts.
If all the other points are satisfied feel free to close the issue.
