### ISSUE TITLE
Create the list of standard commercial parts

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#79]
preliminary sketch that will move to WIKI

**Comment by marcellosavoldi** [comment]
## Hexagon socket cap head
![image](https://user-images.githubusercontent.com/53296021/141816642-f3c7711e-57db-4a54-a7e7-76d7adf1bfc0.png)
|   UNI  |   ISO  |  DIN  | file CAD        | Notes             |
|:------:|:------:|:------|:----------------|:------------------|
|  5931  |  4762  |  912  |  uni5931.prt    |                   |

Dimensions: M3, M4, M5, M6, M8, M10, M12
length : all standard length ( as possible fully tread )
material : Stainless steel
type and class : A2-70

## Hexagon socket countersink head
![image](https://user-images.githubusercontent.com/53296021/141817717-ba6b7caa-eb8d-4a7a-8acf-aadd130330c9.png)
|   UNI  |   ISO      |    DIN  | file CAD          | Notes                 |
|:-------:|:---------:|:--------|:----------------|:------------------|
|  5933  |   10642  |  7991  |  uni5933.prt    |                           |

Dimensions: M3, M4, M5, M6, M8, M10, M12
length : all standard length
material : Stainless steel
type and class : A2-70

## Pozidrive cross recessed pan head
![image](https://user-images.githubusercontent.com/53296021/141818316-b50232ce-ef59-4467-9f15-b28686c6c2f4.png)
|   UNI  |   ISO      |    DIN    |     file CAD          | Notes                 |
|:-------:|:---------:|:---------|:------------------|:------------------|
|  7686  |   7045   |  7985A   |  iso7045_z.prt    |                           |

Dimensions: M1.6, M2, M2.5, M3
length : all standard length
material : Stainless steel
type and class : A2-70

## Philips cross recessed flat head
![image](https://user-images.githubusercontent.com/53296021/141818964-1f465d68-2064-4743-aaab-3d2421910006.png)
|   UNI  |   ISO      |    DIN    |     file CAD          | Notes                 |
|:-------:|:---------:|:---------|:------------------|:------------------|
|  7688  |   7046   |   965A   |  iso7046_h.prt    |                           |

Dimensions: M1.6, M2, M2.5, M3
length : all standard length
material : Stainless steel
type and class : A2-70

**Comment by marcellosavoldi** [comment]
## Hexagon nuts
![image](https://user-images.githubusercontent.com/53296021/142447851-6ce5fb72-7123-4833-9efb-267c9944bf5e.png)
|   UNI  |    ISO  |  DIN  | file CAD          | Notes             |
|:-------:|:-------:|:------|:----------------|:------------------|
|  5588  |  4032  |  934  |  iso4032.prt    |                   |

Dimensions: M1.6, M2, M2.5, M3, M4, M5, M6, M8, M10, M12, M16, M20
material : Stainless steel

Dimensions: M2.5, M3, M4, M5, M6
material : Nylon

**Comment by fiorisi** [comment]
@marcellosavoldi I close this issue.
We already have the wiki sections to edit.

**Comment by marcellosavoldi** [comment]
I need this issue to download the images and copy the link on the wiki.... it's the faster way!

**Comment by marcellosavoldi** [comment]
![image](https://user-images.githubusercontent.com/53296021/148742513-981ffe30-9476-489d-84df-dee40d610b75.png)
![image](https://user-images.githubusercontent.com/53296021/148742704-0c10fb5a-d1c7-4822-8e43-b4d58e59cac5.png)
![image](https://user-images.githubusercontent.com/53296021/148742792-cc07b8ea-7e9d-4c3d-a3e4-ada2baebcecc.png)
![image](https://user-images.githubusercontent.com/53296021/148742897-b69e01d9-1f5b-444c-a2d8-e2d716c29698.png)

**Comment by marcellosavoldi** [comment]
![image](https://user-images.githubusercontent.com/53296021/148745140-1da6141f-a915-4abd-9a9a-8cc477ca8ac4.png)
![image](https://user-images.githubusercontent.com/53296021/148745155-eae12680-ad79-445c-bee4-3eb035fda8ed.png)
![image](https://user-images.githubusercontent.com/53296021/148745183-3e99c5e9-3315-466d-b4b3-de24e212946c.png)
![image](https://user-images.githubusercontent.com/53296021/148745200-ee19325d-e14d-4c00-a7ff-2666165bfa0f.png)
