### ISSUE TITLE
[iso7045_z] - [looking for a code and supplier about the missing screw M3x14]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#8]
| |  |
|:---|:---|
| Alias Creo | V3-14--_-_ISO7045_CZ|
| IIT-Code | 2542 |
| Applicant | Marcello Savoldi, @marcellosavoldi  |
| supervisor | Luca FIorio, @fiorisi  |
| Assignees | Filippo Biggi, @fbiggi  |

Description and motivation of the changing request:

We have to use the family table ISO7045_Z and remove every where the screws ISO7045_H
The first (Z) have represented from the pozidrive cross recessed shape.
The second (H) have represented from the Philips cross recessed shape.

**Comment by marcellosavoldi** [comment]
@fbiggi , Did you write to the supplier?
lagosta@bossard.com

**Comment by fbiggi** [comment]
si attendo info in merito @marcellosavoldi

**Comment by fbiggi** [comment]
RISPOSTA DEL FORNITORE

Buongiorno sig. Biggi ,

grazie per la sua gentile richiesta e per averci chiamati in causa , le allego la ns gamma attualmente disponibile a catalogo per l’articolo menzionato :

Passiamo quindi da una M3 x 12 a una M3 x 16 , quindi la misura richiesta le confermo che non è gestita !  Per avere la misura corrispondente M3 x 14 il lotto minimo produttivo e pari a 100k pcs e normalmente con un LT pari a 14/16 settimane.
Mi faccia sapere se posso aiutarla in qualsiasi altro modo e rimango in attesa di un suo gradito riscontro alla presente .



![image](https://user-images.githubusercontent.com/20420331/99251278-56bf5e00-280d-11eb-9873-60098cbc756d.png)

**Comment by fbiggi** [comment]
@marcellosavoldi 
Attendo risposte per la A4 perché il (tra parentesi) significa disponibile a richiesta (verifica disponibilitá su magazzino)

**Comment by marcellosavoldi** [comment]
.... in effetti comprarne 100 mila non so se ne valga la pena....

**Comment by fiorisi** [comment]
cc @icub-tech-iit/silo-mech

**Comment by fbiggi** [comment]
allego offerta del fornitore
[BOSSARD_QUOTE_370270416.pdf](https://github.com/icub-tech-iit/cad-libraries/files/5573147/BOSSARD_QUOTE_370270416.pdf)

**Comment by marcellosavoldi** [comment]
@fiorisi, @fbiggi  , ne prenderei 1000 (1K) e mettiamole a magazzino ( M3x14).

Possiamo inserirle in family table , variando il materiale nella descrizione....

**Comment by fbiggi** [comment]
@marcellosavoldi se e materiale per iCub sará sotto gestione @Fabrizio69 ?  o compriamo come dev?

**Comment by fbiggi** [comment]
consegna 4-5 gg lavorativi

**Comment by marcellosavoldi** [comment]
se @fiorisi  è daccordo procederei con un purchase per un ordine minimo di 500 pezzi.
Possiamo verificare con @Fabrizio69 , se è il caso di ordinare anche altre viti che stanno per scarseggiare, in modo da fare un ordine cumulativo ( compriamo per il reparto , non per DEV )

A questo punto direi di inserire in family table la famigerata vite e sostituirla in tutti gli assiemi. Varierei la descrizione , mettendo il materiale corretto nella sola istanza. Cosa dite @fiorisi e @Mick3Lozzo ?

**Comment by fiorisi** [comment]
@marcellosavoldi perfetto, procediamo pure con 'ordine!

**Comment by Fabrizio69** [comment]
Ciao @marcellosavoldi in questo momento abbiamo in corso [questo ordine](https://github.com/icub-tech-iit/purchases/issues/827), se volete aggiungere materiale, metto in cc @maggia80 e se per lui va bene, credo non ci siano problemi. Scusate il ritardo....
Ciao

cc: @fiorisi @fbiggi

**Comment by Mick3Lozzo** [comment]
@fbiggi @marcellosavoldi la vite è stata normalizzata a WinGST? È stato aggiunto il costruttore ed il fornitore?

**Comment by maggia80** [comment]
> @fbiggi @marcellosavoldi la vite è stata normalizzata a WinGST. È stato aggiunto il costruttore ed il fornitore.
> 
> Ho un dubbio, considero la Bossard 1581767 per entrambi i campi o come fornitore metto Bulloneria Emiliana?

se entrambi vendono questo componente puoi mettere entrambi i fornitori.

**Comment by Mick3Lozzo** [comment]
Fatto, secondo me questa issue si potrebbe chiudere.

**Comment by fiorisi** [comment]
Thanks @Mick3Lozzo! Just two minor comments:

The `Mitor` supplier was already there and it is still valid?
![image](https://user-images.githubusercontent.com/8970230/104922510-1f029d00-599b-11eb-9886-3ded6115d098.png)

The description needs to be updated with `INOX A4`. 
![image](https://user-images.githubusercontent.com/8970230/104923229-0e9ef200-599c-11eb-8572-dd84a8418e8d.png)

**Comment by Mick3Lozzo** [comment]
@fiorisi updated description.
I don't know if Mitor is still valid as a supplier, but anyway I can't delete it. Only @Fabrizio69 can.

**Comment by Fabrizio69** [comment]
Hi @Mick3Lozzo , Mitor is a used supplier (see the orders in the past), so nobody can delete this supplier.

cc: @fiorisi

**Comment by Fabrizio69** [comment]
Hi @Mick3Lozzo , Mitor is a used supplier (see the orders in the past), so nobody can delete this supplier.

cc: @fiorisi
