### ISSUE TITLE
[Kontron] - [	COMe-mAL10 E2 E3950 8E] - [COM Express mini type10 board]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/cad-libraries#82]
| Description          | COM-Express Type10, Kontron COMe-mAL10 E2 E3950 8E                             |
|:---------------------|:---------------------------------------|
| Datasheet component  | [COMe-mAL10(E2)](https://www.kontron.com/en/products/come-mal10-e2-come-m4al10-e2-/p145439)                |
| Project              | ergoCub     |
| Alias Creo           | KONTRON_COME-MAL10_E2                       |
| IIT-Code             | 15624                   |
| Applicant            |  @Elio75               |
| Supervisor           |  @fiorisi                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
[come-mal10_20201211_datasheet.pdf](https://github.com/icub-tech-iit/cad-libraries/files/7718771/come-mal10_20201211_datasheet.pdf)

![come-mal10_pca](https://user-images.githubusercontent.com/53298662/146175386-5ef148b6-67b7-4f89-97db-7bb6a3b825e3.JPG)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by fiorisi** [comment]
Great @Elio75.
If you commit the file we can check it.

**Comment by Elio75** [comment]
Done

@fiorisi

**Comment by fiorisi** [comment]
@Elio75 can you also add the parameters?
![image](https://user-images.githubusercontent.com/8970230/146338245-83c4066e-de4b-4cad-869f-6f5371ebb327.png)

**Comment by Elio75** [comment]
Done

**Comment by Elio75** [comment]
`Where did you take the mass of the board?`

![image](https://user-images.githubusercontent.com/53298662/146756566-6835c343-f2a7-4bd8-92fa-dac588500dd2.png)

dall`analisi di creo ho preso il volume e diviso per massa per calcolare la densità 

@fiorisi

**Comment by fiorisi** [comment]
Great @Elio75.
Please always add the picture if the mass is not reported in the datasheet.
