### ISSUE TITLE
[Kontron] - [34009-0000-99-2] - [Heatspreader Aluminium with copper plate]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/cad-libraries#83]
| Description          | Heat Sinks HSP COMe-mAL10 E2 slim thread                               |
|:---------------------|:---------------------------------------|
| Datasheet component  | [link or attachment ]                  |
| Project              | ergoCub     |
| Alias Creo           | KONTRON_34009-0000-99-2_R11                         |
| IIT-Code             | 15625                        |
| Applicant            |  @Elio75                |
| Supervisor           |  @fiorisi               |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
[34009-0000-99-2 R11.pdf](https://github.com/icub-tech-iit/cad-libraries/files/7718823/34009-0000-99-2.R11.pdf)

![COME-MAL10_HEATSPREADER_SLIM](https://user-images.githubusercontent.com/53298662/146176018-3f484b22-85ba-4aed-8a56-47b7908a2bbb.JPG)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by fiorisi** [comment]
@Elio75 can you also add the part parameters? I think that we can add a checkpoint also for this.

![image](https://user-images.githubusercontent.com/8970230/146336690-2cd539ee-ce77-45f0-a7a4-fb63a35a9b44.png)

**Comment by Elio75** [comment]
DONE

@fiorisi
