### ISSUE TITLE
[Kontron] - [34099-0000-99-0] - [Heatsink fan]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/cad-libraries#84]
| Description          | COMe mini Active Uni Cooler (w/o HSP)                               |
|:---------------------|:---------------------------------------|
| Datasheet component  | [link or attachment ]                  |
| Project              | ergoCub     |
| Alias Creo           | KONTRON_34099-0000-99-0_R2_1                    |
| IIT-Code             | 15626                        |
| Applicant            |  @Elio75                |
| Supervisor           |  @fiorisi                |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:
[34099-0000-99-0_R21.pdf](https://github.com/icub-tech-iit/cad-libraries/files/7718970/34099-0000-99-0_R21.pdf)

![COME-MAL10_ACTIVE_COOLER](https://user-images.githubusercontent.com/53298662/146179371-bec4ea5a-c31c-42d6-8b70-759e0c3cf439.JPG)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [ ] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by fiorisi** [comment]
@Elio75 can you also add the part parameters? 

![image](https://user-images.githubusercontent.com/8970230/146337808-eedc8974-73aa-4f4d-9f7f-c0ea10b7ce7b.png)

**Comment by fiorisi** [comment]
@Elio75 did you address the [previous comment](https://github.com/icub-tech-iit/cad-libraries/issues/84#issuecomment-995559632)?

**Comment by Elio75** [comment]
Done
