### ISSUE TITLE
ECAD - [AEDR-9820] - [IIT-CODE] - [Reflective Incremental Encoders]

### ISSUE THREAD

**Issue by marcellosavoldi** [icub-tech-iit/cad-libraries#89]
| Description        | Field                                 | Notes |
|:-------------------|:--------------------------------------|:------|
| Datasheet          | see [HERE](https://docs.broadcom.com/doc/AEDR-9830-3-Channels-Reflective-Incremental-Encoders-Output-318-LPI)              |       |
| Manufacturer info  | [Broadcom + AEDR-9830] * |       |
| Alias Creo         | [AEDR-9830] \**          |       |
| MCAD Contact       | Marcello Savoldi @marcellosavoldi                |       |
| ECAD Contact       | Maurizio Borgagni @maurizbo               |       |
| Maintainer         | Marcello Savoldi, @marcellosavoldi    |       |

Legend:  
 - "\*" = To compile only if this information are missing in the database (Wingst)  
 - "\**" = To compile only if it is a preliminary name

### Image with origin e PIN 1 position by PADS (mandatory)
![image](https://user-images.githubusercontent.com/53296021/150562901-8036cfc8-847a-4cd3-933c-dac1fc9d33b8.png)

###  Attachments (optional)
![image](https://user-images.githubusercontent.com/53296021/150563029-d09d4299-55a2-4583-9f42-35e5ec21a713.png)
![image](https://user-images.githubusercontent.com/53296021/150563307-09eaaf85-5f27-4709-b297-53d3699e2545.png)

### Checklist:
- [x] Added IIT-CODE from [WINGST](http://wingst.icub.iit.local/).
- [x] Added assignees (min. 1 mechanical + 1 electrical contact).
- [x] Added Link/datasheet/drawing or others information (or information into Wingst database compiled).
- [x] Added details about the PIN 1 and the orientation of the origin of the component (img/sketch/print-screen).
- [x] Added details about the PLUG connector (added datasheet, or Wingst code).
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).

**Comment by marcellosavoldi** [comment]
done!

**Comment by MrAndrea** [comment]
Title changed with the right model AEDR-9830 and iitcode 16143.
