### ISSUE TITLE
Repo management - Remove outside collaborators w/ read permission once the repo is public

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/cad-libraries#9]
Once this repo will be made public, we no longer need to handle outside collaborators w/ `read` permission.
Therefore, @fiorisi please open up a corresponding PR in https://github.com/icub-tech-iit/outside-collaborators.

**Comment by fiorisi** [comment]
Done in https://github.com/icub-tech-iit/outside-collaborators/pull/16.
