### ISSUE TITLE
[Sauter] - [FH500] - [500 N dynamometer]

### ISSUE THREAD

**Issue by Andrea-Mor** [icub-tech-iit/cad-libraries#90]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | [link or attachment ]                  |
| Project              | -    |
| Alias Creo           | sauter_fh500                         |
| IIT-Code             | [if available]                         |
| Applicant            | Andrea Mor @Andrea-Mor                |
| Supervisor           | Luca Fiorio @fiorisi                 |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Attachment:

[sauter_fh500.prt.zip](https://github.com/icub-tech-iit/cad-libraries/files/8042530/sauter_fh500.prt.zip)

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [ ] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Andrea-Mor** [comment]
## Component mass

Sauter FH500 [datasheet](https://dok.kern-sohn.com/manuals/files/Italian/fh-ba-it-2020.pdf)

![image](https://user-images.githubusercontent.com/79802725/153446177-088388fc-d9ff-4ba3-8d95-94bf02cf5adc.png)

![IMG_0594](https://user-images.githubusercontent.com/79802725/153446317-55eb62f1-191d-47d6-ac64-ce665fc9a61c.jpg)
![IMG_0595](https://user-images.githubusercontent.com/79802725/153446324-7b0c0475-32f8-47c7-96b7-48d5f1221b1a.jpg)

6.3 N = 0,642 kg ✔️

**Comment by Andrea-Mor** [comment]
@fiorisi I ask your help for the last three points of the first comment

> Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.


I think this is not my case.

>  Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).


do I have to convert it?

>  Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

again, this is not our case?

**Comment by Andrea-Mor** [comment]
Design of the Dynamometer changed. An error was fixed

**Comment by Andrea-Mor** [comment]
@fiorisi do I have to do something else?

I've converted the prt file with EDU-COM liecnse and I've checked that there's no special case for this component. 
As long as we don't have to create a IIT code in Wingst, it's all done!

**Comment by fiorisi** [comment]
Thanks @Andrea-Mor. I think that we can close the issue.
