### ISSUE TITLE
IGUS - GSM-0506-046 - sleeve bearing

### ISSUE THREAD

**Issue by Lawproto** [icub-tech-iit/cad-libraries#94]
| Description          | Field                                  |
|:---------------------|:---------------------------------------|
| Datasheet component  | https://www.igus.it/product?artNr=GSM-0506-046 |
| Project              | ergoCub lower arm (Mk2) |
| Alias Creo           | IGUS_GSM-0506-046          |
| IIT-Code             | 16215                    |
| Applicant            | Lorenzo Protopapa, @Lawproto       |
| Supervisor           | Luca Fiorio, @fiorisi             |
| Maintainer           | Marcello Savoldi, @marcellosavoldi     |
| Coworkers            | @icub-tech-iit/silo-mech               |

### Checklist:
Complete the checklist in order to proceed with the request.

- [x] Created the Alias following [the standard convention](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#commercial-components-coding-standard).
- [x] Added, if necessary, the source files (STEP, IGS, etc), the links/datasheets/drawings or other information used to create the library part.
- [x] File imported using the Creo [start part commercial](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components).
- [x] Checked [mass properties](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#mass-properties-of-commercial-parts).
- [x] Checked if one [special case](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#special-cases-and-examples) applies to this component.
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Created IIT code in [WINGST](http://wingst.icub.iit.local/) with manufacturer and at least one supplier.

**Comment by Lawproto** [comment]
Checklist complete. Item added to `cad-libraries` and WinGST. Closing.

**Comment by fiorisi** [comment]
@Lawproto did you use the correct start part? 
https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components

**Comment by Lawproto** [comment]
> @Lawproto did you use the correct start part? https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#standard-part-for-commercial-components

No, I simply assigned the Iglidur material in this case.

**Comment by fiorisi** [comment]
Ok, then simply remove these parameters from the part. 
![image](https://user-images.githubusercontent.com/8970230/161565387-8f9cdc27-dc85-4b40-835c-757636501369.png)

**Comment by Lawproto** [comment]
I see your point, @fiorisi. Fixed that.
