### ISSUE TITLE
Editing [DIN7984]-[correcting material]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/cad-libraries#99]
| Description   | Field                              |
|:--------------|:-----------------------------------|
| Category      | [ECAD-MCAD]                        |
| Alias Creo    | DIN7984                   |
| IIT-Code      | not available - screw family table           |
| Applicant     | Michele Gesino, @Mick3Lozzo             |
| Supervisor    | Ugo Pattacini, @pattacini        |
| Maintainer    | Marcello Savoldi, @marcellosavoldi |
| Coworkers     | @icub-tech-iit/silo-mech           |

## Description and motivation of the changing request: <br>
This family table has not correctly set the material properties. The correct material of the component is steel Aisi 304 (asked telephonically to the supplier).

## Checklist:
- [x] Converted the files with the [EDU-COM license](https://github.com/icub-tech-iit/cad-libraries/wiki/PTC-Creo-Guidelines#save-file-with-commercial-license).
- [x] Checked that the associated [WINGST](http://wingst.icub.iit.local/) code is up-to-date and that the manufacturer and at least one supplier are defined.

**Comment by fiorisi** [comment]
> The correct material of the component is steel Aisi 304 (asked telephonically to the supplier).

The AISI 304 is generally class A@ steel. Did you as the state (annealed, hardened, etc)?
Depending on the state one can define the resistance of the material. 
See https://github.com/icub-tech-iit/cad-mechanics/wiki/Technical-specification-standards#screws-bolts-and-nuts

**Comment by marcellosavoldi** [comment]
Are you speaking about these 2 screws?
![image](https://user-images.githubusercontent.com/53296021/173012626-79922e2f-2212-4c95-a9d0-0c537e3297d1.png)

The Bossard code in wingst is [BN2844](https://www.bossard.com/eshop/global-en/screws-and-bolts-with-internal-drive/hex-socket-head-cap-screws-with-low-head-partially-fully-threaded/p/2844/?category=&index=0&q=bn2844%3Arelevance#tab-features)...
the material type indicated as "A2" only...

checking in the [Wurth website](https://eshop.wuerth.it/Categorie-di-prodotti/DIN-7984-acciaio-inossidabile-A2/31143511140116.cyid/3114.cgid/it/IT/EUR/?CampaignName=SR001&VisibleSearchTerm=din7984) I found the same screws with the material Type "A2-70" ; the same of the torx screws...

Do you think we can use the same?

![image](https://user-images.githubusercontent.com/53296021/173013540-9e2a0421-c0e4-4cd9-987a-be7a9a91aefc.png)

**Comment by Mick3Lozzo** [comment]
@fiorisi @marcellosavoldi can we close this issue?

**Comment by fiorisi** [comment]
> @fiorisi @marcellosavoldi can we close this issue?

Yes, let's use the A2-70.
